# generated by datamodel-codegen:
#   filename:  v2/CommandExecResponse.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class CommandExecResponse(BaseModel):
    exitCode: int = Field(..., description='Process exit code.')
    stderr: str = Field(
        ...,
        description='Buffered stderr capture.\n\nEmpty when stderr was streamed via `command/exec/outputDelta`.',
    )
    stdout: str = Field(
        ...,
        description='Buffered stdout capture.\n\nEmpty when stdout was streamed via `command/exec/outputDelta`.',
    )
