# generated by datamodel-codegen:
#   filename:  v2/ContextCompactedNotification.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel


class ContextCompactedNotification(BaseModel):
    threadId: str
    turnId: str
