# generated by datamodel-codegen:
#   filename:  v2/ExperimentalFeatureEnablementSetResponse.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ExperimentalFeatureEnablementSetResponse(BaseModel):
    enablement: dict[str, bool] = Field(
        ..., description='Feature enablement entries updated by this request.'
    )
