# generated by datamodel-codegen:
#   filename:  v2/ExperimentalFeatureListParams.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class ExperimentalFeatureListParams(BaseModel):
    cursor: str | None = Field(
        None, description='Opaque pagination cursor returned by a previous call.'
    )
    limit: conint(ge=0) | None = Field(
        None,
        description='Optional page size; defaults to a reasonable server-side value.',
    )
