# generated by datamodel-codegen:
#   filename:  v2/ExternalAgentConfigImportParams.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class ExternalAgentConfigMigrationItemType(Enum):
    AGENTS_MD = 'AGENTS_MD'
    CONFIG = 'CONFIG'
    SKILLS = 'SKILLS'
    PLUGINS = 'PLUGINS'
    MCP_SERVER_CONFIG = 'MCP_SERVER_CONFIG'


class PluginsMigration(BaseModel):
    marketplaceName: str
    pluginNames: list[str]


class MigrationDetails(BaseModel):
    plugins: list[PluginsMigration]


class ExternalAgentConfigMigrationItem(BaseModel):
    cwd: str | None = Field(
        None,
        description='Null or empty means home-scoped migration; non-empty means repo-scoped migration.',
    )
    description: str
    details: MigrationDetails | None = None
    itemType: ExternalAgentConfigMigrationItemType


class ExternalAgentConfigImportParams(BaseModel):
    migrationItems: list[ExternalAgentConfigMigrationItem]
