# generated by datamodel-codegen:
#   filename:  v2/FsRemoveResponse.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel


class FsRemoveResponse(BaseModel):
    pass
