# generated by datamodel-codegen:
#   filename:  v2/FsReadFileResponse.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class FsReadFileResponse(BaseModel):
    dataBase64: str = Field(..., description='File contents encoded as base64.')
