# generated by datamodel-codegen:
#   filename:  v2/FsRemoveParams.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class FsRemoveParams(BaseModel):
    force: bool | None = Field(
        None, description='Whether missing paths should be ignored. Defaults to `true`.'
    )
    path: AbsolutePathBuf = Field(..., description='Absolute path to remove.')
    recursive: bool | None = Field(
        None,
        description='Whether directory removal should recurse. Defaults to `true`.',
    )
