# generated by datamodel-codegen:
#   filename:  v2/GetAccountParams.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class GetAccountParams(BaseModel):
    refreshToken: bool | None = Field(
        False,
        description='When `true`, requests a proactive token refresh before returning.\n\nIn managed auth mode this triggers the normal refresh-token flow. In external auth mode this flag is ignored. Clients should refresh tokens themselves and call `account/login/start` with `chatgptAuthTokens`.',
    )
