# generated by datamodel-codegen:
#   filename:  v2/GuardianWarningNotification.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class GuardianWarningNotification(BaseModel):
    message: str = Field(
        ..., description='Concise guardian warning message for the user.'
    )
    threadId: str = Field(..., description='Thread target for the guardian warning.')
