# generated by datamodel-codegen:
#   filename:  v2/HookCompletedNotification.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class HookEventName(Enum):
    preToolUse = 'preToolUse'
    permissionRequest = 'permissionRequest'
    postToolUse = 'postToolUse'
    sessionStart = 'sessionStart'
    userPromptSubmit = 'userPromptSubmit'
    stop = 'stop'


class HookExecutionMode(Enum):
    sync = 'sync'
    async_ = 'async'


class HookHandlerType(Enum):
    command = 'command'
    prompt = 'prompt'
    agent = 'agent'


class HookOutputEntryKind(Enum):
    warning = 'warning'
    stop = 'stop'
    feedback = 'feedback'
    context = 'context'
    error = 'error'


class HookRunStatus(Enum):
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    blocked = 'blocked'
    stopped = 'stopped'


class HookScope(Enum):
    thread = 'thread'
    turn = 'turn'


class HookSource(Enum):
    system = 'system'
    user = 'user'
    project = 'project'
    mdm = 'mdm'
    sessionFlags = 'sessionFlags'
    legacyManagedConfigFile = 'legacyManagedConfigFile'
    legacyManagedConfigMdm = 'legacyManagedConfigMdm'
    unknown = 'unknown'


class HookOutputEntry(BaseModel):
    kind: HookOutputEntryKind
    text: str


class HookRunSummary(BaseModel):
    completedAt: int | None = None
    displayOrder: int
    durationMs: int | None = None
    entries: list[HookOutputEntry]
    eventName: HookEventName
    executionMode: HookExecutionMode
    handlerType: HookHandlerType
    id: str
    scope: HookScope
    source: HookSource | None = 'unknown'
    sourcePath: AbsolutePathBuf
    startedAt: int
    status: HookRunStatus
    statusMessage: str | None = None


class HookCompletedNotification(BaseModel):
    run: HookRunSummary
    threadId: str
    turnId: str | None = None
