# generated by datamodel-codegen:
#   filename:  v2/ItemGuardianApprovalReviewStartedNotification.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class AdditionalNetworkPermissions(BaseModel):
    enabled: bool | None = None


class FileSystemAccessMode(Enum):
    read = 'read'
    write = 'write'
    none = 'none'


class Type(Enum):
    path = 'path'


class FileSystemPath(BaseModel):
    path: AbsolutePathBuf
    type: Type = Field(..., title='PathFileSystemPathType')


class Type146(Enum):
    glob_pattern = 'glob_pattern'


class FileSystemPath18(BaseModel):
    pattern: str
    type: Type146 = Field(..., title='GlobPatternFileSystemPathType')


class Type147(Enum):
    special = 'special'


class Kind(Enum):
    root = 'root'


class FileSystemSpecialPath29(BaseModel):
    kind: Kind


class Kind29(Enum):
    minimal = 'minimal'


class FileSystemSpecialPath30(BaseModel):
    kind: Kind29


class Kind30(Enum):
    current_working_directory = 'current_working_directory'


class FileSystemSpecialPath31(BaseModel):
    kind: Kind30


class Kind31(Enum):
    project_roots = 'project_roots'


class FileSystemSpecialPath32(BaseModel):
    kind: Kind31
    subpath: str | None = None


class Kind32(Enum):
    tmpdir = 'tmpdir'


class FileSystemSpecialPath33(BaseModel):
    kind: Kind32


class Kind33(Enum):
    slash_tmp = 'slash_tmp'


class FileSystemSpecialPath34(BaseModel):
    kind: Kind33


class Kind34(Enum):
    unknown = 'unknown'


class FileSystemSpecialPath35(BaseModel):
    kind: Kind34
    path: str
    subpath: str | None = None


class FileSystemSpecialPath(
    RootModel[
        FileSystemSpecialPath29
        | FileSystemSpecialPath30
        | FileSystemSpecialPath31
        | FileSystemSpecialPath32
        | FileSystemSpecialPath33
        | FileSystemSpecialPath34
        | FileSystemSpecialPath35
    ]
):
    root: (
        FileSystemSpecialPath29
        | FileSystemSpecialPath30
        | FileSystemSpecialPath31
        | FileSystemSpecialPath32
        | FileSystemSpecialPath33
        | FileSystemSpecialPath34
        | FileSystemSpecialPath35
    )


class Type148(Enum):
    command = 'command'


class Type149(Enum):
    execve = 'execve'


class Type150(Enum):
    applyPatch = 'applyPatch'


class GuardianApprovalReviewAction9(BaseModel):
    cwd: AbsolutePathBuf
    files: list[AbsolutePathBuf]
    type: Type150 = Field(..., title='ApplyPatchGuardianApprovalReviewActionType')


class Type151(Enum):
    networkAccess = 'networkAccess'


class Type152(Enum):
    mcpToolCall = 'mcpToolCall'


class GuardianApprovalReviewAction11(BaseModel):
    connectorId: str | None = None
    connectorName: str | None = None
    server: str
    toolName: str
    toolTitle: str | None = None
    type: Type152 = Field(..., title='McpToolCallGuardianApprovalReviewActionType')


class Type153(Enum):
    requestPermissions = 'requestPermissions'


class GuardianApprovalReviewStatus(Enum):
    inProgress = 'inProgress'
    approved = 'approved'
    denied = 'denied'
    timedOut = 'timedOut'
    aborted = 'aborted'


class GuardianCommandSource(Enum):
    shell = 'shell'
    unifiedExec = 'unifiedExec'


class GuardianRiskLevel(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class GuardianUserAuthorization(Enum):
    unknown = 'unknown'
    low = 'low'
    medium = 'medium'
    high = 'high'


class NetworkApprovalProtocol(Enum):
    http = 'http'
    https = 'https'
    socks5Tcp = 'socks5Tcp'
    socks5Udp = 'socks5Udp'


class FileSystemPath19(BaseModel):
    type: Type147 = Field(..., title='SpecialFileSystemPathType')
    value: FileSystemSpecialPath


class FileSystemPath16(RootModel[FileSystemPath | FileSystemPath18 | FileSystemPath19]):
    root: FileSystemPath | FileSystemPath18 | FileSystemPath19


class FileSystemSandboxEntry(BaseModel):
    access: FileSystemAccessMode
    path: FileSystemPath16


class GuardianApprovalReview(BaseModel):
    rationale: str | None = None
    riskLevel: GuardianRiskLevel | None = None
    status: GuardianApprovalReviewStatus
    userAuthorization: GuardianUserAuthorization | None = None


class GuardianApprovalReviewAction7(BaseModel):
    command: str
    cwd: AbsolutePathBuf
    source: GuardianCommandSource
    type: Type148 = Field(..., title='CommandGuardianApprovalReviewActionType')


class GuardianApprovalReviewAction8(BaseModel):
    argv: list[str]
    cwd: AbsolutePathBuf
    program: str
    source: GuardianCommandSource
    type: Type149 = Field(..., title='ExecveGuardianApprovalReviewActionType')


class GuardianApprovalReviewAction10(BaseModel):
    host: str
    port: conint(ge=0)
    protocol: NetworkApprovalProtocol
    target: str
    type: Type151 = Field(..., title='NetworkAccessGuardianApprovalReviewActionType')


class AdditionalFileSystemPermissions(BaseModel):
    entries: list[FileSystemSandboxEntry] | None = None
    globScanMaxDepth: conint(ge=1) | None = None
    read: list[AbsolutePathBuf] | None = Field(
        None, description='This will be removed in favor of `entries`.'
    )
    write: list[AbsolutePathBuf] | None = Field(
        None, description='This will be removed in favor of `entries`.'
    )


class RequestPermissionProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fileSystem: AdditionalFileSystemPermissions | None = None
    network: AdditionalNetworkPermissions | None = None


class GuardianApprovalReviewAction12(BaseModel):
    permissions: RequestPermissionProfile
    reason: str | None = None
    type: Type153 = Field(
        ..., title='RequestPermissionsGuardianApprovalReviewActionType'
    )


class GuardianApprovalReviewAction(
    RootModel[
        GuardianApprovalReviewAction7
        | GuardianApprovalReviewAction8
        | GuardianApprovalReviewAction9
        | GuardianApprovalReviewAction10
        | GuardianApprovalReviewAction11
        | GuardianApprovalReviewAction12
    ]
):
    root: (
        GuardianApprovalReviewAction7
        | GuardianApprovalReviewAction8
        | GuardianApprovalReviewAction9
        | GuardianApprovalReviewAction10
        | GuardianApprovalReviewAction11
        | GuardianApprovalReviewAction12
    )


class ItemGuardianApprovalReviewStartedNotification(BaseModel):
    action: GuardianApprovalReviewAction
    review: GuardianApprovalReview
    reviewId: str = Field(..., description='Stable identifier for this review.')
    targetItemId: str | None = Field(
        None,
        description='Identifier for the reviewed item or tool call when one exists.\n\nIn most cases, one review maps to one target item. The exceptions are - execve reviews, where a single command may contain multiple execve calls to review (only possible when using the shell_zsh_fork feature) - network policy reviews, where there is no target item\n\nA network call is triggered by a CommandExecution item, so having a target_item_id set to the CommandExecution item would be misleading because the review is about the network call, not the command execution. Therefore, target_item_id is set to None for network policy reviews.',
    )
    threadId: str
    turnId: str
