# generated by datamodel-codegen:
#   filename:  v2/ListMcpServerStatusParams.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, conint


class McpServerStatusDetail(Enum):
    full = 'full'
    toolsAndAuthOnly = 'toolsAndAuthOnly'


class ListMcpServerStatusParams(BaseModel):
    cursor: str | None = Field(
        None, description='Opaque pagination cursor returned by a previous call.'
    )
    detail: McpServerStatusDetail | None = Field(
        None,
        description='Controls how much MCP inventory data to fetch for each server. Defaults to `Full` when omitted.',
    )
    limit: conint(ge=0) | None = Field(
        None, description='Optional page size; defaults to a server-defined value.'
    )
