# generated by datamodel-codegen:
#   filename:  v2/LoginAccountResponse.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class Type(Enum):
    apiKey = 'apiKey'


class LoginAccountResponse1(BaseModel):
    type: Type = Field(..., title='ApiKeyv2::LoginAccountResponseType')


class Type193(Enum):
    chatgpt = 'chatgpt'


class LoginAccountResponse2(BaseModel):
    authUrl: str = Field(
        ...,
        description='URL the client should open in a browser to initiate the OAuth flow.',
    )
    loginId: str
    type: Type193 = Field(..., title='Chatgptv2::LoginAccountResponseType')


class Type194(Enum):
    chatgptDeviceCode = 'chatgptDeviceCode'


class LoginAccountResponse3(BaseModel):
    loginId: str
    type: Type194 = Field(..., title='ChatgptDeviceCodev2::LoginAccountResponseType')
    userCode: str = Field(
        ..., description='One-time code the user must enter after signing in.'
    )
    verificationUrl: str = Field(
        ...,
        description='URL the client should open in a browser to complete device code authorization.',
    )


class Type195(Enum):
    chatgptAuthTokens = 'chatgptAuthTokens'


class LoginAccountResponse4(BaseModel):
    type: Type195 = Field(..., title='ChatgptAuthTokensv2::LoginAccountResponseType')


class LoginAccountResponse(
    RootModel[
        LoginAccountResponse1
        | LoginAccountResponse2
        | LoginAccountResponse3
        | LoginAccountResponse4
    ]
):
    root: (
        LoginAccountResponse1
        | LoginAccountResponse2
        | LoginAccountResponse3
        | LoginAccountResponse4
    ) = Field(..., title='LoginAccountResponse')
