# generated by datamodel-codegen:
#   filename:  v2/McpResourceReadParams.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel


class McpResourceReadParams(BaseModel):
    server: str
    threadId: str | None = None
    uri: str
