# generated by datamodel-codegen:
#   filename:  v2/McpServerOauthLoginParams.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel


class McpServerOauthLoginParams(BaseModel):
    name: str
    scopes: list[str] | None = None
    timeoutSecs: int | None = None
