# generated by datamodel-codegen:
#   filename:  v2/ModelListResponse.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class InputModality1(Enum):
    text = 'text'


class InputModality2(Enum):
    image = 'image'


class InputModality(RootModel[InputModality1 | InputModality2]):
    root: InputModality1 | InputModality2 = Field(
        ..., description='Canonical user-input modality tags advertised by a model.'
    )


class ModelAvailabilityNux(BaseModel):
    message: str


class ModelUpgradeInfo(BaseModel):
    migrationMarkdown: str | None = None
    model: str
    modelLink: str | None = None
    upgradeCopy: str | None = None


class ReasoningEffort(Enum):
    none = 'none'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class ReasoningEffortOption(BaseModel):
    description: str
    reasoningEffort: ReasoningEffort


class Model(BaseModel):
    additionalSpeedTiers: list[str] | None = []
    availabilityNux: ModelAvailabilityNux | None = None
    defaultReasoningEffort: ReasoningEffort
    description: str
    displayName: str
    hidden: bool
    id: str
    inputModalities: list[InputModality] | None = Field(
        ['text', 'image'], validate_default=True
    )
    isDefault: bool
    model: str
    supportedReasoningEfforts: list[ReasoningEffortOption]
    supportsPersonality: bool | None = False
    upgrade: str | None = None
    upgradeInfo: ModelUpgradeInfo | None = None


class ModelListResponse(BaseModel):
    data: list[Model]
    nextCursor: str | None = Field(
        None,
        description='Opaque cursor to pass to the next call to continue after the last item. If None, there are no more items to return.',
    )
