# generated by datamodel-codegen:
#   filename:  v2/PluginInstallResponse.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class AppSummary(BaseModel):
    description: str | None = None
    id: str
    installUrl: str | None = None
    name: str
    needsAuth: bool


class PluginAuthPolicy(Enum):
    ON_INSTALL = 'ON_INSTALL'
    ON_USE = 'ON_USE'


class PluginInstallResponse(BaseModel):
    appsNeedingAuth: list[AppSummary]
    authPolicy: PluginAuthPolicy
