# generated by datamodel-codegen:
#   filename:  v2/ReasoningSummaryTextDeltaNotification.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel


class ReasoningSummaryTextDeltaNotification(BaseModel):
    delta: str
    itemId: str
    summaryIndex: int
    threadId: str
    turnId: str
