# generated by datamodel-codegen:
#   filename:  v2/ReviewStartParams.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class ReviewDelivery(Enum):
    inline = 'inline'
    detached = 'detached'


class Type(Enum):
    uncommittedChanges = 'uncommittedChanges'


class ReviewTarget5(BaseModel):
    type: Type = Field(..., title='UncommittedChangesReviewTargetType')


class Type236(Enum):
    baseBranch = 'baseBranch'


class ReviewTarget6(BaseModel):
    branch: str
    type: Type236 = Field(..., title='BaseBranchReviewTargetType')


class Type237(Enum):
    commit = 'commit'


class ReviewTarget7(BaseModel):
    sha: str
    title: str | None = Field(
        None,
        description='Optional human-readable label (e.g., commit subject) for UIs.',
    )
    type: Type237 = Field(..., title='CommitReviewTargetType')


class Type238(Enum):
    custom = 'custom'


class ReviewTarget8(BaseModel):
    instructions: str
    type: Type238 = Field(..., title='CustomReviewTargetType')


class ReviewTarget(
    RootModel[ReviewTarget5 | ReviewTarget6 | ReviewTarget7 | ReviewTarget8]
):
    root: ReviewTarget5 | ReviewTarget6 | ReviewTarget7 | ReviewTarget8


class ReviewStartParams(BaseModel):
    delivery: ReviewDelivery | None = Field(
        None,
        description='Where to run the review: inline (default) on the current thread or detached on a new thread (returned in `reviewThreadId`).',
    )
    target: ReviewTarget
    threadId: str
