# generated by datamodel-codegen:
#   filename:  v2/ServerRequestResolvedNotification.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel


class RequestId(RootModel[str | int]):
    root: str | int


class ServerRequestResolvedNotification(BaseModel):
    requestId: RequestId
    threadId: str
