# generated by datamodel-codegen:
#   filename:  v2/SkillsListResponse.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class SkillErrorInfo(BaseModel):
    message: str
    path: str


class SkillInterface(BaseModel):
    brandColor: str | None = None
    defaultPrompt: str | None = None
    displayName: str | None = None
    iconLarge: AbsolutePathBuf | None = None
    iconSmall: AbsolutePathBuf | None = None
    shortDescription: str | None = None


class SkillScope(Enum):
    user = 'user'
    repo = 'repo'
    system = 'system'
    admin = 'admin'


class SkillToolDependency(BaseModel):
    command: str | None = None
    description: str | None = None
    transport: str | None = None
    type: str
    url: str | None = None
    value: str


class SkillDependencies(BaseModel):
    tools: list[SkillToolDependency]


class SkillMetadata(BaseModel):
    dependencies: SkillDependencies | None = None
    description: str
    enabled: bool
    interface: SkillInterface | None = None
    name: str
    path: AbsolutePathBuf
    scope: SkillScope
    shortDescription: str | None = Field(
        None,
        description='Legacy short_description from SKILL.md. Prefer SKILL.json interface.short_description.',
    )


class SkillsListEntry(BaseModel):
    cwd: str
    errors: list[SkillErrorInfo]
    skills: list[SkillMetadata]


class SkillsListResponse(BaseModel):
    data: list[SkillsListEntry]
