# generated by datamodel-codegen:
#   filename:  v2/ThreadResumeResponse.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class AgentPath(RootModel[str]):
    root: str


class ApprovalsReviewer(Enum):
    user = 'user'
    auto_review = 'auto_review'
    guardian_subagent = 'guardian_subagent'


class AskForApproval15(Enum):
    untrusted = 'untrusted'
    on_failure = 'on-failure'
    on_request = 'on-request'
    never = 'never'


class Granular(BaseModel):
    mcp_elicitations: bool
    request_permissions: bool | None = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool | None = False


class AskForApproval16(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    granular: Granular


class AskForApproval(RootModel[AskForApproval15 | AskForApproval16]):
    root: AskForApproval15 | AskForApproval16


class ByteRange(BaseModel):
    end: conint(ge=0)
    start: conint(ge=0)


class CodexErrorInfo(Enum):
    contextWindowExceeded = 'contextWindowExceeded'
    usageLimitExceeded = 'usageLimitExceeded'
    serverOverloaded = 'serverOverloaded'
    cyberPolicy = 'cyberPolicy'
    internalServerError = 'internalServerError'
    unauthorized = 'unauthorized'
    badRequest = 'badRequest'
    threadRollbackFailed = 'threadRollbackFailed'
    sandboxError = 'sandboxError'
    other = 'other'


class HttpConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo51(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    httpConnectionFailed: HttpConnectionFailed


class ResponseStreamConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo52(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamConnectionFailed: ResponseStreamConnectionFailed


class ResponseStreamDisconnected(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo53(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamDisconnected: ResponseStreamDisconnected


class ResponseTooManyFailedAttempts(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo54(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseTooManyFailedAttempts: ResponseTooManyFailedAttempts


class CollabAgentStatus(Enum):
    pendingInit = 'pendingInit'
    running = 'running'
    interrupted = 'interrupted'
    completed = 'completed'
    errored = 'errored'
    shutdown = 'shutdown'
    notFound = 'notFound'


class CollabAgentTool(Enum):
    spawnAgent = 'spawnAgent'
    sendInput = 'sendInput'
    resumeAgent = 'resumeAgent'
    wait = 'wait'
    closeAgent = 'closeAgent'


class CollabAgentToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class Type(Enum):
    read = 'read'


class CommandAction(BaseModel):
    command: str
    name: str
    path: AbsolutePathBuf
    type: Type = Field(..., title='ReadCommandActionType')


class Type529(Enum):
    listFiles = 'listFiles'


class CommandAction52(BaseModel):
    command: str
    path: str | None = None
    type: Type529 = Field(..., title='ListFilesCommandActionType')


class Type530(Enum):
    search = 'search'


class CommandAction53(BaseModel):
    command: str
    path: str | None = None
    query: str | None = None
    type: Type530 = Field(..., title='SearchCommandActionType')


class Type531(Enum):
    unknown = 'unknown'


class CommandAction54(BaseModel):
    command: str
    type: Type531 = Field(..., title='UnknownCommandActionType')


class CommandAction50(
    RootModel[CommandAction | CommandAction52 | CommandAction53 | CommandAction54]
):
    root: CommandAction | CommandAction52 | CommandAction53 | CommandAction54


class CommandExecutionSource(Enum):
    agent = 'agent'
    userShell = 'userShell'
    unifiedExecStartup = 'unifiedExecStartup'
    unifiedExecInteraction = 'unifiedExecInteraction'


class CommandExecutionStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type532(Enum):
    inputText = 'inputText'


class DynamicToolCallOutputContentItem(BaseModel):
    text: str
    type: Type532 = Field(..., title='InputTextDynamicToolCallOutputContentItemType')


class Type533(Enum):
    inputImage = 'inputImage'


class DynamicToolCallOutputContentItem29(BaseModel):
    imageUrl: str
    type: Type533 = Field(..., title='InputImageDynamicToolCallOutputContentItemType')


class DynamicToolCallOutputContentItem27(
    RootModel[DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem29]
):
    root: DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem29


class DynamicToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class FileSystemAccessMode(Enum):
    read = 'read'
    write = 'write'
    none = 'none'


class Type534(Enum):
    path = 'path'


class FileSystemPath(BaseModel):
    path: AbsolutePathBuf
    type: Type534 = Field(..., title='PathFileSystemPathType')


class Type535(Enum):
    glob_pattern = 'glob_pattern'


class FileSystemPath50(BaseModel):
    pattern: str
    type: Type535 = Field(..., title='GlobPatternFileSystemPathType')


class Type536(Enum):
    special = 'special'


class Kind(Enum):
    root = 'root'


class FileSystemSpecialPath85(BaseModel):
    kind: Kind


class Kind85(Enum):
    minimal = 'minimal'


class FileSystemSpecialPath86(BaseModel):
    kind: Kind85


class Kind86(Enum):
    current_working_directory = 'current_working_directory'


class FileSystemSpecialPath87(BaseModel):
    kind: Kind86


class Kind87(Enum):
    project_roots = 'project_roots'


class FileSystemSpecialPath88(BaseModel):
    kind: Kind87
    subpath: str | None = None


class Kind88(Enum):
    tmpdir = 'tmpdir'


class FileSystemSpecialPath89(BaseModel):
    kind: Kind88


class Kind89(Enum):
    slash_tmp = 'slash_tmp'


class FileSystemSpecialPath90(BaseModel):
    kind: Kind89


class Kind90(Enum):
    unknown = 'unknown'


class FileSystemSpecialPath91(BaseModel):
    kind: Kind90
    path: str
    subpath: str | None = None


class FileSystemSpecialPath(
    RootModel[
        FileSystemSpecialPath85
        | FileSystemSpecialPath86
        | FileSystemSpecialPath87
        | FileSystemSpecialPath88
        | FileSystemSpecialPath89
        | FileSystemSpecialPath90
        | FileSystemSpecialPath91
    ]
):
    root: (
        FileSystemSpecialPath85
        | FileSystemSpecialPath86
        | FileSystemSpecialPath87
        | FileSystemSpecialPath88
        | FileSystemSpecialPath89
        | FileSystemSpecialPath90
        | FileSystemSpecialPath91
    )


class GitInfo(BaseModel):
    branch: str | None = None
    originUrl: str | None = None
    sha: str | None = None


class HookPromptFragment(BaseModel):
    hookRunId: str
    text: str


class McpToolCallError(BaseModel):
    message: str


class McpToolCallResult(BaseModel):
    field_meta: Any | None = Field(None, alias='_meta')
    content: list[Any]
    structuredContent: Any | None = None


class McpToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class MemoryCitationEntry(BaseModel):
    lineEnd: conint(ge=0)
    lineStart: conint(ge=0)
    note: str
    path: str


class MessagePhase(Enum):
    commentary = 'commentary'


class MessagePhase35(Enum):
    final_answer = 'final_answer'


class MessagePhase33(RootModel[MessagePhase | MessagePhase35]):
    root: MessagePhase | MessagePhase35 = Field(
        ...,
        description='Classifies an assistant message as interim commentary or final answer text.\n\nProviders do not emit this consistently, so callers must treat `None` as "phase unknown" and keep compatibility behavior for legacy models.',
    )


class NetworkAccess(Enum):
    restricted = 'restricted'
    enabled = 'enabled'


class NonSteerableTurnKind(Enum):
    review = 'review'
    compact = 'compact'


class PatchApplyStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type537(Enum):
    add = 'add'


class PatchChangeKind28(BaseModel):
    type: Type537 = Field(..., title='AddPatchChangeKindType')


class Type538(Enum):
    delete = 'delete'


class PatchChangeKind29(BaseModel):
    type: Type538 = Field(..., title='DeletePatchChangeKindType')


class Type539(Enum):
    update = 'update'


class PatchChangeKind30(BaseModel):
    move_path: str | None = None
    type: Type539 = Field(..., title='UpdatePatchChangeKindType')


class PatchChangeKind(
    RootModel[PatchChangeKind28 | PatchChangeKind29 | PatchChangeKind30]
):
    root: PatchChangeKind28 | PatchChangeKind29 | PatchChangeKind30


class PermissionProfileNetworkPermissions(BaseModel):
    enabled: bool | None = None


class Type540(Enum):
    restricted = 'restricted'


class ReadOnlyAccess(BaseModel):
    includePlatformDefaults: bool | None = True
    readableRoots: list[AbsolutePathBuf] | None = Field([], validate_default=True)
    type: Type540 = Field(..., title='RestrictedReadOnlyAccessType')


class Type541(Enum):
    fullAccess = 'fullAccess'


class ReadOnlyAccess11(BaseModel):
    type: Type541 = Field(..., title='FullAccessReadOnlyAccessType')


class ReadOnlyAccess9(RootModel[ReadOnlyAccess | ReadOnlyAccess11]):
    root: ReadOnlyAccess | ReadOnlyAccess11


class ReasoningEffort(Enum):
    none = 'none'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class Type542(Enum):
    dangerFullAccess = 'dangerFullAccess'


class SandboxPolicy13(BaseModel):
    type: Type542 = Field(..., title='DangerFullAccessSandboxPolicyType')


class Type543(Enum):
    readOnly = 'readOnly'


class SandboxPolicy14(BaseModel):
    access: ReadOnlyAccess9 | None = Field(
        {'type': 'fullAccess'}, validate_default=True
    )
    networkAccess: bool | None = False
    type: Type543 = Field(..., title='ReadOnlySandboxPolicyType')


class Type544(Enum):
    externalSandbox = 'externalSandbox'


class SandboxPolicy15(BaseModel):
    networkAccess: NetworkAccess | None = 'restricted'
    type: Type544 = Field(..., title='ExternalSandboxSandboxPolicyType')


class Type545(Enum):
    workspaceWrite = 'workspaceWrite'


class SandboxPolicy16(BaseModel):
    excludeSlashTmp: bool | None = False
    excludeTmpdirEnvVar: bool | None = False
    networkAccess: bool | None = False
    readOnlyAccess: ReadOnlyAccess9 | None = Field(
        {'type': 'fullAccess'}, validate_default=True
    )
    type: Type545 = Field(..., title='WorkspaceWriteSandboxPolicyType')
    writableRoots: list[AbsolutePathBuf] | None = Field([], validate_default=True)


class SandboxPolicy(
    RootModel[SandboxPolicy13 | SandboxPolicy14 | SandboxPolicy15 | SandboxPolicy16]
):
    root: SandboxPolicy13 | SandboxPolicy14 | SandboxPolicy15 | SandboxPolicy16


class ServiceTier(Enum):
    fast = 'fast'
    flex = 'flex'


class SessionSource(Enum):
    cli = 'cli'
    vscode = 'vscode'
    exec = 'exec'
    appServer = 'appServer'
    unknown = 'unknown'


class SessionSource22(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    custom: str


class SubAgentSource16(Enum):
    review = 'review'
    compact = 'compact'
    memory_consolidation = 'memory_consolidation'


class SubAgentSource18(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    other: str


class TextElement(BaseModel):
    byteRange: ByteRange = Field(
        ...,
        description='Byte range in the parent `text` buffer that this element occupies.',
    )
    placeholder: str | None = Field(
        None,
        description='Optional human-readable placeholder for the element, displayed in the UI.',
    )


class ThreadActiveFlag(Enum):
    waitingOnApproval = 'waitingOnApproval'
    waitingOnUserInput = 'waitingOnUserInput'


class ThreadId(RootModel[str]):
    root: str


class Type546(Enum):
    userMessage = 'userMessage'


class Type547(Enum):
    hookPrompt = 'hookPrompt'


class ThreadItem(BaseModel):
    fragments: list[HookPromptFragment]
    id: str
    type: Type547 = Field(..., title='HookPromptThreadItemType')


class Type548(Enum):
    agentMessage = 'agentMessage'


class Type549(Enum):
    plan = 'plan'


class ThreadItem138(BaseModel):
    id: str
    text: str
    type: Type549 = Field(..., title='PlanThreadItemType')


class Type550(Enum):
    reasoning = 'reasoning'


class ThreadItem139(BaseModel):
    content: list[str] | None = []
    id: str
    summary: list[str] | None = []
    type: Type550 = Field(..., title='ReasoningThreadItemType')


class Type551(Enum):
    commandExecution = 'commandExecution'


class ThreadItem140(BaseModel):
    aggregatedOutput: str | None = Field(
        None, description="The command's output, aggregated from stdout and stderr."
    )
    command: str = Field(..., description='The command to be executed.')
    commandActions: list[CommandAction50] = Field(
        ...,
        description='A best-effort parsing of the command to understand the action(s) it will perform. This returns a list of CommandAction objects because a single shell command may be composed of many commands piped together.',
    )
    cwd: AbsolutePathBuf = Field(..., description="The command's working directory.")
    durationMs: int | None = Field(
        None, description='The duration of the command execution in milliseconds.'
    )
    exitCode: int | None = Field(None, description="The command's exit code.")
    id: str
    processId: str | None = Field(
        None, description='Identifier for the underlying PTY process (when available).'
    )
    source: CommandExecutionSource | None = 'agent'
    status: CommandExecutionStatus
    type: Type551 = Field(..., title='CommandExecutionThreadItemType')


class Type552(Enum):
    fileChange = 'fileChange'


class Type553(Enum):
    mcpToolCall = 'mcpToolCall'


class ThreadItem142(BaseModel):
    arguments: Any
    durationMs: int | None = Field(
        None, description='The duration of the MCP tool call in milliseconds.'
    )
    error: McpToolCallError | None = None
    id: str
    mcpAppResourceUri: str | None = None
    result: McpToolCallResult | None = None
    server: str
    status: McpToolCallStatus
    tool: str
    type: Type553 = Field(..., title='McpToolCallThreadItemType')


class Type554(Enum):
    dynamicToolCall = 'dynamicToolCall'


class ThreadItem143(BaseModel):
    arguments: Any
    contentItems: list[DynamicToolCallOutputContentItem27] | None = None
    durationMs: int | None = Field(
        None, description='The duration of the dynamic tool call in milliseconds.'
    )
    id: str
    namespace: str | None = None
    status: DynamicToolCallStatus
    success: bool | None = None
    tool: str
    type: Type554 = Field(..., title='DynamicToolCallThreadItemType')


class Type555(Enum):
    collabAgentToolCall = 'collabAgentToolCall'


class Type556(Enum):
    webSearch = 'webSearch'


class Type557(Enum):
    imageView = 'imageView'


class ThreadItem146(BaseModel):
    id: str
    path: AbsolutePathBuf
    type: Type557 = Field(..., title='ImageViewThreadItemType')


class Type558(Enum):
    imageGeneration = 'imageGeneration'


class ThreadItem147(BaseModel):
    id: str
    result: str
    revisedPrompt: str | None = None
    savedPath: AbsolutePathBuf | None = None
    status: str
    type: Type558 = Field(..., title='ImageGenerationThreadItemType')


class Type559(Enum):
    enteredReviewMode = 'enteredReviewMode'


class ThreadItem148(BaseModel):
    id: str
    review: str
    type: Type559 = Field(..., title='EnteredReviewModeThreadItemType')


class Type560(Enum):
    exitedReviewMode = 'exitedReviewMode'


class ThreadItem149(BaseModel):
    id: str
    review: str
    type: Type560 = Field(..., title='ExitedReviewModeThreadItemType')


class Type561(Enum):
    contextCompaction = 'contextCompaction'


class ThreadItem150(BaseModel):
    id: str
    type: Type561 = Field(..., title='ContextCompactionThreadItemType')


class Type562(Enum):
    notLoaded = 'notLoaded'


class ThreadStatus21(BaseModel):
    type: Type562 = Field(..., title='NotLoadedThreadStatusType')


class Type563(Enum):
    idle = 'idle'


class ThreadStatus22(BaseModel):
    type: Type563 = Field(..., title='IdleThreadStatusType')


class Type564(Enum):
    systemError = 'systemError'


class ThreadStatus23(BaseModel):
    type: Type564 = Field(..., title='SystemErrorThreadStatusType')


class Type565(Enum):
    active = 'active'


class ThreadStatus24(BaseModel):
    activeFlags: list[ThreadActiveFlag]
    type: Type565 = Field(..., title='ActiveThreadStatusType')


class ThreadStatus(
    RootModel[ThreadStatus21 | ThreadStatus22 | ThreadStatus23 | ThreadStatus24]
):
    root: ThreadStatus21 | ThreadStatus22 | ThreadStatus23 | ThreadStatus24


class TurnStatus(Enum):
    completed = 'completed'
    interrupted = 'interrupted'
    failed = 'failed'
    inProgress = 'inProgress'


class Type566(Enum):
    text = 'text'


class UserInput46(BaseModel):
    text: str
    text_elements: list[TextElement] | None = Field(
        [],
        description='UI-defined spans within `text` used to render or persist special elements.',
        validate_default=True,
    )
    type: Type566 = Field(..., title='TextUserInputType')


class Type567(Enum):
    image = 'image'


class UserInput47(BaseModel):
    type: Type567 = Field(..., title='ImageUserInputType')
    url: str


class Type568(Enum):
    localImage = 'localImage'


class UserInput48(BaseModel):
    path: str
    type: Type568 = Field(..., title='LocalImageUserInputType')


class Type569(Enum):
    skill = 'skill'


class UserInput49(BaseModel):
    name: str
    path: str
    type: Type569 = Field(..., title='SkillUserInputType')


class Type570(Enum):
    mention = 'mention'


class UserInput50(BaseModel):
    name: str
    path: str
    type: Type570 = Field(..., title='MentionUserInputType')


class UserInput(
    RootModel[UserInput46 | UserInput47 | UserInput48 | UserInput49 | UserInput50]
):
    root: UserInput46 | UserInput47 | UserInput48 | UserInput49 | UserInput50


class Type571(Enum):
    search = 'search'


class WebSearchAction33(BaseModel):
    queries: list[str] | None = None
    query: str | None = None
    type: Type571 = Field(..., title='SearchWebSearchActionType')


class Type572(Enum):
    openPage = 'openPage'


class WebSearchAction34(BaseModel):
    type: Type572 = Field(..., title='OpenPageWebSearchActionType')
    url: str | None = None


class Type573(Enum):
    findInPage = 'findInPage'


class WebSearchAction35(BaseModel):
    pattern: str | None = None
    type: Type573 = Field(..., title='FindInPageWebSearchActionType')
    url: str | None = None


class Type574(Enum):
    other = 'other'


class WebSearchAction36(BaseModel):
    type: Type574 = Field(..., title='OtherWebSearchActionType')


class WebSearchAction(
    RootModel[
        WebSearchAction33 | WebSearchAction34 | WebSearchAction35 | WebSearchAction36
    ]
):
    root: WebSearchAction33 | WebSearchAction34 | WebSearchAction35 | WebSearchAction36


class ActiveTurnNotSteerable(BaseModel):
    turnKind: NonSteerableTurnKind


class CodexErrorInfo55(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeTurnNotSteerable: ActiveTurnNotSteerable


class CodexErrorInfo49(
    RootModel[
        CodexErrorInfo
        | CodexErrorInfo51
        | CodexErrorInfo52
        | CodexErrorInfo53
        | CodexErrorInfo54
        | CodexErrorInfo55
    ]
):
    root: (
        CodexErrorInfo
        | CodexErrorInfo51
        | CodexErrorInfo52
        | CodexErrorInfo53
        | CodexErrorInfo54
        | CodexErrorInfo55
    ) = Field(
        ...,
        description='This translation layer make sure that we expose codex error code in camel case.\n\nWhen an upstream HTTP status is available (for example, from the Responses API or a provider), it is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.',
    )


class CollabAgentState(BaseModel):
    message: str | None = None
    status: CollabAgentStatus


class FileSystemPath51(BaseModel):
    type: Type536 = Field(..., title='SpecialFileSystemPathType')
    value: FileSystemSpecialPath


class FileSystemPath48(RootModel[FileSystemPath | FileSystemPath50 | FileSystemPath51]):
    root: FileSystemPath | FileSystemPath50 | FileSystemPath51


class FileSystemSandboxEntry(BaseModel):
    access: FileSystemAccessMode
    path: FileSystemPath48


class FileUpdateChange(BaseModel):
    diff: str
    kind: PatchChangeKind
    path: str


class MemoryCitation(BaseModel):
    entries: list[MemoryCitationEntry]
    threadIds: list[str]


class PermissionProfileFileSystemPermissions(BaseModel):
    entries: list[FileSystemSandboxEntry]
    globScanMaxDepth: conint(ge=1) | None = None


class ThreadSpawn(BaseModel):
    agent_nickname: str | None = None
    agent_path: AgentPath | None = None
    agent_role: str | None = None
    depth: int
    parent_thread_id: ThreadId


class SubAgentSource17(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    thread_spawn: ThreadSpawn


class SubAgentSource(RootModel[SubAgentSource16 | SubAgentSource17 | SubAgentSource18]):
    root: SubAgentSource16 | SubAgentSource17 | SubAgentSource18


class ThreadItem135(BaseModel):
    content: list[UserInput]
    id: str
    type: Type546 = Field(..., title='UserMessageThreadItemType')


class ThreadItem137(BaseModel):
    id: str
    memoryCitation: MemoryCitation | None = None
    phase: MessagePhase33 | None = None
    text: str
    type: Type548 = Field(..., title='AgentMessageThreadItemType')


class ThreadItem141(BaseModel):
    changes: list[FileUpdateChange]
    id: str
    status: PatchApplyStatus
    type: Type552 = Field(..., title='FileChangeThreadItemType')


class ThreadItem144(BaseModel):
    agentsStates: dict[str, CollabAgentState] = Field(
        ..., description='Last known status of the target agents, when available.'
    )
    id: str = Field(..., description='Unique identifier for this collab tool call.')
    model: str | None = Field(
        None, description='Model requested for the spawned agent, when applicable.'
    )
    prompt: str | None = Field(
        None,
        description='Prompt text sent as part of the collab tool call, when available.',
    )
    reasoningEffort: ReasoningEffort | None = Field(
        None,
        description='Reasoning effort requested for the spawned agent, when applicable.',
    )
    receiverThreadIds: list[str] = Field(
        ...,
        description='Thread ID of the receiving agent, when applicable. In case of spawn operation, this corresponds to the newly spawned agent.',
    )
    senderThreadId: str = Field(
        ..., description='Thread ID of the agent issuing the collab request.'
    )
    status: CollabAgentToolCallStatus = Field(
        ..., description='Current status of the collab tool call.'
    )
    tool: CollabAgentTool = Field(
        ..., description='Name of the collab tool that was invoked.'
    )
    type: Type555 = Field(..., title='CollabAgentToolCallThreadItemType')


class ThreadItem145(BaseModel):
    action: WebSearchAction | None = None
    id: str
    query: str
    type: Type556 = Field(..., title='WebSearchThreadItemType')


class ThreadItem134(
    RootModel[
        ThreadItem135
        | ThreadItem
        | ThreadItem137
        | ThreadItem138
        | ThreadItem139
        | ThreadItem140
        | ThreadItem141
        | ThreadItem142
        | ThreadItem143
        | ThreadItem144
        | ThreadItem145
        | ThreadItem146
        | ThreadItem147
        | ThreadItem148
        | ThreadItem149
        | ThreadItem150
    ]
):
    root: (
        ThreadItem135
        | ThreadItem
        | ThreadItem137
        | ThreadItem138
        | ThreadItem139
        | ThreadItem140
        | ThreadItem141
        | ThreadItem142
        | ThreadItem143
        | ThreadItem144
        | ThreadItem145
        | ThreadItem146
        | ThreadItem147
        | ThreadItem148
        | ThreadItem149
        | ThreadItem150
    )


class TurnError(BaseModel):
    additionalDetails: str | None = None
    codexErrorInfo: CodexErrorInfo49 | None = None
    message: str


class PermissionProfile(BaseModel):
    fileSystem: PermissionProfileFileSystemPermissions | None = None
    network: PermissionProfileNetworkPermissions | None = None


class SessionSource23(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subAgent: SubAgentSource


class SessionSource20(RootModel[SessionSource | SessionSource22 | SessionSource23]):
    root: SessionSource | SessionSource22 | SessionSource23


class Turn(BaseModel):
    completedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn completed.'
    )
    durationMs: int | None = Field(
        None,
        description='Duration between turn start and completion in milliseconds, if known.',
    )
    error: TurnError | None = Field(
        None, description="Only populated when the Turn's status is failed."
    )
    id: str
    items: list[ThreadItem134] = Field(
        ...,
        description='Only populated on a `thread/resume` or `thread/fork` response. For all other responses and notifications returning a Turn, the items field will be an empty list.',
    )
    startedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn started.'
    )
    status: TurnStatus


class Thread(BaseModel):
    agentNickname: str | None = Field(
        None,
        description='Optional random unique nickname assigned to an AgentControl-spawned sub-agent.',
    )
    agentRole: str | None = Field(
        None,
        description='Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.',
    )
    cliVersion: str = Field(
        ..., description='Version of the CLI that created the thread.'
    )
    createdAt: int = Field(
        ..., description='Unix timestamp (in seconds) when the thread was created.'
    )
    cwd: AbsolutePathBuf = Field(
        ..., description='Working directory captured for the thread.'
    )
    ephemeral: bool = Field(
        ...,
        description='Whether the thread is ephemeral and should not be materialized on disk.',
    )
    forkedFromId: str | None = Field(
        None,
        description='Source thread id when this thread was created by forking another thread.',
    )
    gitInfo: GitInfo | None = Field(
        None, description='Optional Git metadata captured when the thread was created.'
    )
    id: str
    modelProvider: str = Field(
        ..., description="Model provider used for this thread (for example, 'openai')."
    )
    name: str | None = Field(None, description='Optional user-facing thread title.')
    path: str | None = Field(None, description='[UNSTABLE] Path to the thread on disk.')
    preview: str = Field(
        ..., description='Usually the first user message in the thread, if available.'
    )
    source: SessionSource20 = Field(
        ...,
        description='Origin of the thread (CLI, VSCode, codex exec, codex app-server, etc.).',
    )
    status: ThreadStatus = Field(
        ..., description='Current runtime status for the thread.'
    )
    turns: list[Turn] = Field(
        ...,
        description='Only populated on `thread/resume`, `thread/rollback`, `thread/fork`, and `thread/read` (when `includeTurns` is true) responses. For all other responses and notifications returning a Thread, the turns field will be an empty list.',
    )
    updatedAt: int = Field(
        ..., description='Unix timestamp (in seconds) when the thread was last updated.'
    )


class ThreadResumeResponse(BaseModel):
    approvalPolicy: AskForApproval
    approvalsReviewer: ApprovalsReviewer = Field(
        ..., description='Reviewer currently used for approval requests on this thread.'
    )
    cwd: AbsolutePathBuf
    instructionSources: list[AbsolutePathBuf] | None = Field(
        [],
        description='Instruction source files currently loaded for this thread.',
        validate_default=True,
    )
    model: str
    modelProvider: str
    permissionProfile: PermissionProfile | None = Field(
        None,
        description='Canonical active permissions view for this thread when representable. This is `null` for external sandbox policies because external enforcement cannot be round-tripped as a `PermissionProfile`.',
    )
    reasoningEffort: ReasoningEffort | None = None
    sandbox: SandboxPolicy = Field(
        ...,
        description='Legacy sandbox policy retained for compatibility. New clients should use `permissionProfile` when present as the canonical active permissions view.',
    )
    serviceTier: ServiceTier | None = None
    thread: Thread
