# generated by datamodel-codegen:
#   filename:  v2/ThreadUnsubscribeResponse.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class ThreadUnsubscribeStatus(Enum):
    notLoaded = 'notLoaded'
    notSubscribed = 'notSubscribed'
    unsubscribed = 'unsubscribed'


class ThreadUnsubscribeResponse(BaseModel):
    status: ThreadUnsubscribeStatus
