# generated by datamodel-codegen:
#   filename:  v2/ThreadLoadedListResponse.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ThreadLoadedListResponse(BaseModel):
    data: list[str] = Field(
        ..., description='Thread ids for sessions currently loaded in memory.'
    )
    nextCursor: str | None = Field(
        None,
        description='Opaque cursor to pass to the next call to continue after the last item. if None, there are no more items to return.',
    )
