# generated by datamodel-codegen:
#   filename:  v2/ThreadTurnsListResponse.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class ByteRange(BaseModel):
    end: conint(ge=0)
    start: conint(ge=0)


class CodexErrorInfo(Enum):
    contextWindowExceeded = 'contextWindowExceeded'
    usageLimitExceeded = 'usageLimitExceeded'
    serverOverloaded = 'serverOverloaded'
    cyberPolicy = 'cyberPolicy'
    internalServerError = 'internalServerError'
    unauthorized = 'unauthorized'
    badRequest = 'badRequest'
    threadRollbackFailed = 'threadRollbackFailed'
    sandboxError = 'sandboxError'
    other = 'other'


class HttpConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo79(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    httpConnectionFailed: HttpConnectionFailed


class ResponseStreamConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo80(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamConnectionFailed: ResponseStreamConnectionFailed


class ResponseStreamDisconnected(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo81(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamDisconnected: ResponseStreamDisconnected


class ResponseTooManyFailedAttempts(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo82(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseTooManyFailedAttempts: ResponseTooManyFailedAttempts


class CollabAgentStatus(Enum):
    pendingInit = 'pendingInit'
    running = 'running'
    interrupted = 'interrupted'
    completed = 'completed'
    errored = 'errored'
    shutdown = 'shutdown'
    notFound = 'notFound'


class CollabAgentTool(Enum):
    spawnAgent = 'spawnAgent'
    sendInput = 'sendInput'
    resumeAgent = 'resumeAgent'
    wait = 'wait'
    closeAgent = 'closeAgent'


class CollabAgentToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class Type(Enum):
    read = 'read'


class CommandAction(BaseModel):
    command: str
    name: str
    path: AbsolutePathBuf
    type: Type = Field(..., title='ReadCommandActionType')


class Type706(Enum):
    listFiles = 'listFiles'


class CommandAction72(BaseModel):
    command: str
    path: str | None = None
    type: Type706 = Field(..., title='ListFilesCommandActionType')


class Type707(Enum):
    search = 'search'


class CommandAction73(BaseModel):
    command: str
    path: str | None = None
    query: str | None = None
    type: Type707 = Field(..., title='SearchCommandActionType')


class Type708(Enum):
    unknown = 'unknown'


class CommandAction74(BaseModel):
    command: str
    type: Type708 = Field(..., title='UnknownCommandActionType')


class CommandAction70(
    RootModel[CommandAction | CommandAction72 | CommandAction73 | CommandAction74]
):
    root: CommandAction | CommandAction72 | CommandAction73 | CommandAction74


class CommandExecutionSource(Enum):
    agent = 'agent'
    userShell = 'userShell'
    unifiedExecStartup = 'unifiedExecStartup'
    unifiedExecInteraction = 'unifiedExecInteraction'


class CommandExecutionStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type709(Enum):
    inputText = 'inputText'


class DynamicToolCallOutputContentItem(BaseModel):
    text: str
    type: Type709 = Field(..., title='InputTextDynamicToolCallOutputContentItemType')


class Type710(Enum):
    inputImage = 'inputImage'


class DynamicToolCallOutputContentItem41(BaseModel):
    imageUrl: str
    type: Type710 = Field(..., title='InputImageDynamicToolCallOutputContentItemType')


class DynamicToolCallOutputContentItem39(
    RootModel[DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem41]
):
    root: DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem41


class DynamicToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class HookPromptFragment(BaseModel):
    hookRunId: str
    text: str


class McpToolCallError(BaseModel):
    message: str


class McpToolCallResult(BaseModel):
    field_meta: Any | None = Field(None, alias='_meta')
    content: list[Any]
    structuredContent: Any | None = None


class McpToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class MemoryCitationEntry(BaseModel):
    lineEnd: conint(ge=0)
    lineStart: conint(ge=0)
    note: str
    path: str


class MessagePhase(Enum):
    commentary = 'commentary'


class MessagePhase47(Enum):
    final_answer = 'final_answer'


class MessagePhase45(RootModel[MessagePhase | MessagePhase47]):
    root: MessagePhase | MessagePhase47 = Field(
        ...,
        description='Classifies an assistant message as interim commentary or final answer text.\n\nProviders do not emit this consistently, so callers must treat `None` as "phase unknown" and keep compatibility behavior for legacy models.',
    )


class NonSteerableTurnKind(Enum):
    review = 'review'
    compact = 'compact'


class PatchApplyStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type711(Enum):
    add = 'add'


class PatchChangeKind40(BaseModel):
    type: Type711 = Field(..., title='AddPatchChangeKindType')


class Type712(Enum):
    delete = 'delete'


class PatchChangeKind41(BaseModel):
    type: Type712 = Field(..., title='DeletePatchChangeKindType')


class Type713(Enum):
    update = 'update'


class PatchChangeKind42(BaseModel):
    move_path: str | None = None
    type: Type713 = Field(..., title='UpdatePatchChangeKindType')


class PatchChangeKind(
    RootModel[PatchChangeKind40 | PatchChangeKind41 | PatchChangeKind42]
):
    root: PatchChangeKind40 | PatchChangeKind41 | PatchChangeKind42


class ReasoningEffort(Enum):
    none = 'none'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class TextElement(BaseModel):
    byteRange: ByteRange = Field(
        ...,
        description='Byte range in the parent `text` buffer that this element occupies.',
    )
    placeholder: str | None = Field(
        None,
        description='Optional human-readable placeholder for the element, displayed in the UI.',
    )


class Type714(Enum):
    userMessage = 'userMessage'


class Type715(Enum):
    hookPrompt = 'hookPrompt'


class ThreadItem(BaseModel):
    fragments: list[HookPromptFragment]
    id: str
    type: Type715 = Field(..., title='HookPromptThreadItemType')


class Type716(Enum):
    agentMessage = 'agentMessage'


class Type717(Enum):
    plan = 'plan'


class ThreadItem206(BaseModel):
    id: str
    text: str
    type: Type717 = Field(..., title='PlanThreadItemType')


class Type718(Enum):
    reasoning = 'reasoning'


class ThreadItem207(BaseModel):
    content: list[str] | None = []
    id: str
    summary: list[str] | None = []
    type: Type718 = Field(..., title='ReasoningThreadItemType')


class Type719(Enum):
    commandExecution = 'commandExecution'


class ThreadItem208(BaseModel):
    aggregatedOutput: str | None = Field(
        None, description="The command's output, aggregated from stdout and stderr."
    )
    command: str = Field(..., description='The command to be executed.')
    commandActions: list[CommandAction70] = Field(
        ...,
        description='A best-effort parsing of the command to understand the action(s) it will perform. This returns a list of CommandAction objects because a single shell command may be composed of many commands piped together.',
    )
    cwd: AbsolutePathBuf = Field(..., description="The command's working directory.")
    durationMs: int | None = Field(
        None, description='The duration of the command execution in milliseconds.'
    )
    exitCode: int | None = Field(None, description="The command's exit code.")
    id: str
    processId: str | None = Field(
        None, description='Identifier for the underlying PTY process (when available).'
    )
    source: CommandExecutionSource | None = 'agent'
    status: CommandExecutionStatus
    type: Type719 = Field(..., title='CommandExecutionThreadItemType')


class Type720(Enum):
    fileChange = 'fileChange'


class Type721(Enum):
    mcpToolCall = 'mcpToolCall'


class ThreadItem210(BaseModel):
    arguments: Any
    durationMs: int | None = Field(
        None, description='The duration of the MCP tool call in milliseconds.'
    )
    error: McpToolCallError | None = None
    id: str
    mcpAppResourceUri: str | None = None
    result: McpToolCallResult | None = None
    server: str
    status: McpToolCallStatus
    tool: str
    type: Type721 = Field(..., title='McpToolCallThreadItemType')


class Type722(Enum):
    dynamicToolCall = 'dynamicToolCall'


class ThreadItem211(BaseModel):
    arguments: Any
    contentItems: list[DynamicToolCallOutputContentItem39] | None = None
    durationMs: int | None = Field(
        None, description='The duration of the dynamic tool call in milliseconds.'
    )
    id: str
    namespace: str | None = None
    status: DynamicToolCallStatus
    success: bool | None = None
    tool: str
    type: Type722 = Field(..., title='DynamicToolCallThreadItemType')


class Type723(Enum):
    collabAgentToolCall = 'collabAgentToolCall'


class Type724(Enum):
    webSearch = 'webSearch'


class Type725(Enum):
    imageView = 'imageView'


class ThreadItem214(BaseModel):
    id: str
    path: AbsolutePathBuf
    type: Type725 = Field(..., title='ImageViewThreadItemType')


class Type726(Enum):
    imageGeneration = 'imageGeneration'


class ThreadItem215(BaseModel):
    id: str
    result: str
    revisedPrompt: str | None = None
    savedPath: AbsolutePathBuf | None = None
    status: str
    type: Type726 = Field(..., title='ImageGenerationThreadItemType')


class Type727(Enum):
    enteredReviewMode = 'enteredReviewMode'


class ThreadItem216(BaseModel):
    id: str
    review: str
    type: Type727 = Field(..., title='EnteredReviewModeThreadItemType')


class Type728(Enum):
    exitedReviewMode = 'exitedReviewMode'


class ThreadItem217(BaseModel):
    id: str
    review: str
    type: Type728 = Field(..., title='ExitedReviewModeThreadItemType')


class Type729(Enum):
    contextCompaction = 'contextCompaction'


class ThreadItem218(BaseModel):
    id: str
    type: Type729 = Field(..., title='ContextCompactionThreadItemType')


class TurnStatus(Enum):
    completed = 'completed'
    interrupted = 'interrupted'
    failed = 'failed'
    inProgress = 'inProgress'


class Type730(Enum):
    text = 'text'


class UserInput66(BaseModel):
    text: str
    text_elements: list[TextElement] | None = Field(
        [],
        description='UI-defined spans within `text` used to render or persist special elements.',
        validate_default=True,
    )
    type: Type730 = Field(..., title='TextUserInputType')


class Type731(Enum):
    image = 'image'


class UserInput67(BaseModel):
    type: Type731 = Field(..., title='ImageUserInputType')
    url: str


class Type732(Enum):
    localImage = 'localImage'


class UserInput68(BaseModel):
    path: str
    type: Type732 = Field(..., title='LocalImageUserInputType')


class Type733(Enum):
    skill = 'skill'


class UserInput69(BaseModel):
    name: str
    path: str
    type: Type733 = Field(..., title='SkillUserInputType')


class Type734(Enum):
    mention = 'mention'


class UserInput70(BaseModel):
    name: str
    path: str
    type: Type734 = Field(..., title='MentionUserInputType')


class UserInput(
    RootModel[UserInput66 | UserInput67 | UserInput68 | UserInput69 | UserInput70]
):
    root: UserInput66 | UserInput67 | UserInput68 | UserInput69 | UserInput70


class Type735(Enum):
    search = 'search'


class WebSearchAction49(BaseModel):
    queries: list[str] | None = None
    query: str | None = None
    type: Type735 = Field(..., title='SearchWebSearchActionType')


class Type736(Enum):
    openPage = 'openPage'


class WebSearchAction50(BaseModel):
    type: Type736 = Field(..., title='OpenPageWebSearchActionType')
    url: str | None = None


class Type737(Enum):
    findInPage = 'findInPage'


class WebSearchAction51(BaseModel):
    pattern: str | None = None
    type: Type737 = Field(..., title='FindInPageWebSearchActionType')
    url: str | None = None


class Type738(Enum):
    other = 'other'


class WebSearchAction52(BaseModel):
    type: Type738 = Field(..., title='OtherWebSearchActionType')


class WebSearchAction(
    RootModel[
        WebSearchAction49 | WebSearchAction50 | WebSearchAction51 | WebSearchAction52
    ]
):
    root: WebSearchAction49 | WebSearchAction50 | WebSearchAction51 | WebSearchAction52


class ActiveTurnNotSteerable(BaseModel):
    turnKind: NonSteerableTurnKind


class CodexErrorInfo83(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeTurnNotSteerable: ActiveTurnNotSteerable


class CodexErrorInfo77(
    RootModel[
        CodexErrorInfo
        | CodexErrorInfo79
        | CodexErrorInfo80
        | CodexErrorInfo81
        | CodexErrorInfo82
        | CodexErrorInfo83
    ]
):
    root: (
        CodexErrorInfo
        | CodexErrorInfo79
        | CodexErrorInfo80
        | CodexErrorInfo81
        | CodexErrorInfo82
        | CodexErrorInfo83
    ) = Field(
        ...,
        description='This translation layer make sure that we expose codex error code in camel case.\n\nWhen an upstream HTTP status is available (for example, from the Responses API or a provider), it is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.',
    )


class CollabAgentState(BaseModel):
    message: str | None = None
    status: CollabAgentStatus


class FileUpdateChange(BaseModel):
    diff: str
    kind: PatchChangeKind
    path: str


class MemoryCitation(BaseModel):
    entries: list[MemoryCitationEntry]
    threadIds: list[str]


class ThreadItem203(BaseModel):
    content: list[UserInput]
    id: str
    type: Type714 = Field(..., title='UserMessageThreadItemType')


class ThreadItem205(BaseModel):
    id: str
    memoryCitation: MemoryCitation | None = None
    phase: MessagePhase45 | None = None
    text: str
    type: Type716 = Field(..., title='AgentMessageThreadItemType')


class ThreadItem209(BaseModel):
    changes: list[FileUpdateChange]
    id: str
    status: PatchApplyStatus
    type: Type720 = Field(..., title='FileChangeThreadItemType')


class ThreadItem212(BaseModel):
    agentsStates: dict[str, CollabAgentState] = Field(
        ..., description='Last known status of the target agents, when available.'
    )
    id: str = Field(..., description='Unique identifier for this collab tool call.')
    model: str | None = Field(
        None, description='Model requested for the spawned agent, when applicable.'
    )
    prompt: str | None = Field(
        None,
        description='Prompt text sent as part of the collab tool call, when available.',
    )
    reasoningEffort: ReasoningEffort | None = Field(
        None,
        description='Reasoning effort requested for the spawned agent, when applicable.',
    )
    receiverThreadIds: list[str] = Field(
        ...,
        description='Thread ID of the receiving agent, when applicable. In case of spawn operation, this corresponds to the newly spawned agent.',
    )
    senderThreadId: str = Field(
        ..., description='Thread ID of the agent issuing the collab request.'
    )
    status: CollabAgentToolCallStatus = Field(
        ..., description='Current status of the collab tool call.'
    )
    tool: CollabAgentTool = Field(
        ..., description='Name of the collab tool that was invoked.'
    )
    type: Type723 = Field(..., title='CollabAgentToolCallThreadItemType')


class ThreadItem213(BaseModel):
    action: WebSearchAction | None = None
    id: str
    query: str
    type: Type724 = Field(..., title='WebSearchThreadItemType')


class ThreadItem202(
    RootModel[
        ThreadItem203
        | ThreadItem
        | ThreadItem205
        | ThreadItem206
        | ThreadItem207
        | ThreadItem208
        | ThreadItem209
        | ThreadItem210
        | ThreadItem211
        | ThreadItem212
        | ThreadItem213
        | ThreadItem214
        | ThreadItem215
        | ThreadItem216
        | ThreadItem217
        | ThreadItem218
    ]
):
    root: (
        ThreadItem203
        | ThreadItem
        | ThreadItem205
        | ThreadItem206
        | ThreadItem207
        | ThreadItem208
        | ThreadItem209
        | ThreadItem210
        | ThreadItem211
        | ThreadItem212
        | ThreadItem213
        | ThreadItem214
        | ThreadItem215
        | ThreadItem216
        | ThreadItem217
        | ThreadItem218
    )


class TurnError(BaseModel):
    additionalDetails: str | None = None
    codexErrorInfo: CodexErrorInfo77 | None = None
    message: str


class Turn(BaseModel):
    completedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn completed.'
    )
    durationMs: int | None = Field(
        None,
        description='Duration between turn start and completion in milliseconds, if known.',
    )
    error: TurnError | None = Field(
        None, description="Only populated when the Turn's status is failed."
    )
    id: str
    items: list[ThreadItem202] = Field(
        ...,
        description='Only populated on a `thread/resume` or `thread/fork` response. For all other responses and notifications returning a Turn, the items field will be an empty list.',
    )
    startedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn started.'
    )
    status: TurnStatus


class ThreadTurnsListResponse(BaseModel):
    backwardsCursor: str | None = Field(
        None,
        description='Opaque cursor to pass as `cursor` when reversing `sortDirection`. This is only populated when the page contains at least one turn. Use it with the opposite `sortDirection` to include the anchor turn again and catch updates to that turn.',
    )
    data: list[Turn]
    nextCursor: str | None = Field(
        None,
        description='Opaque cursor to pass to the next call to continue after the last turn. if None, there are no more turns to return.',
    )
