# generated by datamodel-codegen:
#   filename:  v2/ThreadTokenUsageUpdatedNotification.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel


class TokenUsageBreakdown(BaseModel):
    cachedInputTokens: int
    inputTokens: int
    outputTokens: int
    reasoningOutputTokens: int
    totalTokens: int


class ThreadTokenUsage(BaseModel):
    last: TokenUsageBreakdown
    modelContextWindow: int | None = None
    total: TokenUsageBreakdown


class ThreadTokenUsageUpdatedNotification(BaseModel):
    threadId: str
    tokenUsage: ThreadTokenUsage
    turnId: str
