# generated by datamodel-codegen:
#   filename:  v2/ThreadApproveGuardianDeniedActionParams.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ThreadApproveGuardianDeniedActionParams(BaseModel):
    event: Any = Field(
        ...,
        description='Serialized `codex_protocol::protocol::GuardianAssessmentEvent`.',
    )
    threadId: str
