# generated by datamodel-codegen:
#   filename:  v2/ThreadStartParams.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class ApprovalsReviewer(Enum):
    user = 'user'
    auto_review = 'auto_review'
    guardian_subagent = 'guardian_subagent'


class AskForApproval17(Enum):
    untrusted = 'untrusted'
    on_failure = 'on-failure'
    on_request = 'on-request'
    never = 'never'


class Granular(BaseModel):
    mcp_elicitations: bool
    request_permissions: bool | None = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool | None = False


class AskForApproval18(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    granular: Granular


class AskForApproval(RootModel[AskForApproval17 | AskForApproval18]):
    root: AskForApproval17 | AskForApproval18


class DynamicToolSpec(BaseModel):
    deferLoading: bool | None = None
    description: str
    inputSchema: Any
    name: str
    namespace: str | None = None


class FileSystemAccessMode(Enum):
    read = 'read'
    write = 'write'
    none = 'none'


class Type(Enum):
    path = 'path'


class FileSystemPath(BaseModel):
    path: AbsolutePathBuf
    type: Type = Field(..., title='PathFileSystemPathType')


class Type614(Enum):
    glob_pattern = 'glob_pattern'


class FileSystemPath54(BaseModel):
    pattern: str
    type: Type614 = Field(..., title='GlobPatternFileSystemPathType')


class Type615(Enum):
    special = 'special'


class Kind(Enum):
    root = 'root'


class FileSystemSpecialPath92(BaseModel):
    kind: Kind


class Kind92(Enum):
    minimal = 'minimal'


class FileSystemSpecialPath93(BaseModel):
    kind: Kind92


class Kind93(Enum):
    current_working_directory = 'current_working_directory'


class FileSystemSpecialPath94(BaseModel):
    kind: Kind93


class Kind94(Enum):
    project_roots = 'project_roots'


class FileSystemSpecialPath95(BaseModel):
    kind: Kind94
    subpath: str | None = None


class Kind95(Enum):
    tmpdir = 'tmpdir'


class FileSystemSpecialPath96(BaseModel):
    kind: Kind95


class Kind96(Enum):
    slash_tmp = 'slash_tmp'


class FileSystemSpecialPath97(BaseModel):
    kind: Kind96


class Kind97(Enum):
    unknown = 'unknown'


class FileSystemSpecialPath98(BaseModel):
    kind: Kind97
    path: str
    subpath: str | None = None


class FileSystemSpecialPath(
    RootModel[
        FileSystemSpecialPath92
        | FileSystemSpecialPath93
        | FileSystemSpecialPath94
        | FileSystemSpecialPath95
        | FileSystemSpecialPath96
        | FileSystemSpecialPath97
        | FileSystemSpecialPath98
    ]
):
    root: (
        FileSystemSpecialPath92
        | FileSystemSpecialPath93
        | FileSystemSpecialPath94
        | FileSystemSpecialPath95
        | FileSystemSpecialPath96
        | FileSystemSpecialPath97
        | FileSystemSpecialPath98
    )


class PermissionProfileNetworkPermissions(BaseModel):
    enabled: bool | None = None


class Personality(Enum):
    none = 'none'
    friendly = 'friendly'
    pragmatic = 'pragmatic'


class SandboxMode(Enum):
    read_only = 'read-only'
    workspace_write = 'workspace-write'
    danger_full_access = 'danger-full-access'


class ServiceTier(Enum):
    fast = 'fast'
    flex = 'flex'


class ThreadStartSource(Enum):
    startup = 'startup'
    clear = 'clear'


class FileSystemPath55(BaseModel):
    type: Type615 = Field(..., title='SpecialFileSystemPathType')
    value: FileSystemSpecialPath


class FileSystemPath52(RootModel[FileSystemPath | FileSystemPath54 | FileSystemPath55]):
    root: FileSystemPath | FileSystemPath54 | FileSystemPath55


class FileSystemSandboxEntry(BaseModel):
    access: FileSystemAccessMode
    path: FileSystemPath52


class PermissionProfileFileSystemPermissions(BaseModel):
    entries: list[FileSystemSandboxEntry]
    globScanMaxDepth: conint(ge=1) | None = None


class PermissionProfile(BaseModel):
    fileSystem: PermissionProfileFileSystemPermissions | None = None
    network: PermissionProfileNetworkPermissions | None = None


class ThreadStartParams(BaseModel):
    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = Field(
        None,
        description='Override where approval requests are routed for review on this thread and subsequent turns.',
    )
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    sessionStartSource: ThreadStartSource | None = None
    ephemeral: bool | None = None
    serviceName: str | None = None
    sandbox: SandboxMode | None = None
    model: str | None = None
    modelProvider: str | None = None
    permissionProfile: PermissionProfile | None = Field(
        None,
        description='Full permissions override for this thread. Cannot be combined with `sandbox`.',
    )
    serviceTier: ServiceTier | None = None
    personality: Personality | None = None
