# generated by datamodel-codegen:
#   filename:  v2/ThreadReadParams.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ThreadReadParams(BaseModel):
    includeTurns: bool | None = Field(
        False,
        description='When true, include turns and their items from rollout history.',
    )
    threadId: str
