# generated by datamodel-codegen:
#   filename:  v2/ThreadReadResponse.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class AgentPath(RootModel[str]):
    root: str


class ByteRange(BaseModel):
    end: conint(ge=0)
    start: conint(ge=0)


class CodexErrorInfo(Enum):
    contextWindowExceeded = 'contextWindowExceeded'
    usageLimitExceeded = 'usageLimitExceeded'
    serverOverloaded = 'serverOverloaded'
    cyberPolicy = 'cyberPolicy'
    internalServerError = 'internalServerError'
    unauthorized = 'unauthorized'
    badRequest = 'badRequest'
    threadRollbackFailed = 'threadRollbackFailed'
    sandboxError = 'sandboxError'
    other = 'other'


class HttpConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo44(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    httpConnectionFailed: HttpConnectionFailed


class ResponseStreamConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo45(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamConnectionFailed: ResponseStreamConnectionFailed


class ResponseStreamDisconnected(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo46(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamDisconnected: ResponseStreamDisconnected


class ResponseTooManyFailedAttempts(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo47(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseTooManyFailedAttempts: ResponseTooManyFailedAttempts


class CollabAgentStatus(Enum):
    pendingInit = 'pendingInit'
    running = 'running'
    interrupted = 'interrupted'
    completed = 'completed'
    errored = 'errored'
    shutdown = 'shutdown'
    notFound = 'notFound'


class CollabAgentTool(Enum):
    spawnAgent = 'spawnAgent'
    sendInput = 'sendInput'
    resumeAgent = 'resumeAgent'
    wait = 'wait'
    closeAgent = 'closeAgent'


class CollabAgentToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class Type(Enum):
    read = 'read'


class CommandAction(BaseModel):
    command: str
    name: str
    path: AbsolutePathBuf
    type: Type = Field(..., title='ReadCommandActionType')


class Type461(Enum):
    listFiles = 'listFiles'


class CommandAction47(BaseModel):
    command: str
    path: str | None = None
    type: Type461 = Field(..., title='ListFilesCommandActionType')


class Type462(Enum):
    search = 'search'


class CommandAction48(BaseModel):
    command: str
    path: str | None = None
    query: str | None = None
    type: Type462 = Field(..., title='SearchCommandActionType')


class Type463(Enum):
    unknown = 'unknown'


class CommandAction49(BaseModel):
    command: str
    type: Type463 = Field(..., title='UnknownCommandActionType')


class CommandAction45(
    RootModel[CommandAction | CommandAction47 | CommandAction48 | CommandAction49]
):
    root: CommandAction | CommandAction47 | CommandAction48 | CommandAction49


class CommandExecutionSource(Enum):
    agent = 'agent'
    userShell = 'userShell'
    unifiedExecStartup = 'unifiedExecStartup'
    unifiedExecInteraction = 'unifiedExecInteraction'


class CommandExecutionStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type464(Enum):
    inputText = 'inputText'


class DynamicToolCallOutputContentItem(BaseModel):
    text: str
    type: Type464 = Field(..., title='InputTextDynamicToolCallOutputContentItemType')


class Type465(Enum):
    inputImage = 'inputImage'


class DynamicToolCallOutputContentItem26(BaseModel):
    imageUrl: str
    type: Type465 = Field(..., title='InputImageDynamicToolCallOutputContentItemType')


class DynamicToolCallOutputContentItem24(
    RootModel[DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem26]
):
    root: DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem26


class DynamicToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class GitInfo(BaseModel):
    branch: str | None = None
    originUrl: str | None = None
    sha: str | None = None


class HookPromptFragment(BaseModel):
    hookRunId: str
    text: str


class McpToolCallError(BaseModel):
    message: str


class McpToolCallResult(BaseModel):
    field_meta: Any | None = Field(None, alias='_meta')
    content: list[Any]
    structuredContent: Any | None = None


class McpToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class MemoryCitationEntry(BaseModel):
    lineEnd: conint(ge=0)
    lineStart: conint(ge=0)
    note: str
    path: str


class MessagePhase(Enum):
    commentary = 'commentary'


class MessagePhase29(Enum):
    final_answer = 'final_answer'


class MessagePhase27(RootModel[MessagePhase | MessagePhase29]):
    root: MessagePhase | MessagePhase29 = Field(
        ...,
        description='Classifies an assistant message as interim commentary or final answer text.\n\nProviders do not emit this consistently, so callers must treat `None` as "phase unknown" and keep compatibility behavior for legacy models.',
    )


class NonSteerableTurnKind(Enum):
    review = 'review'
    compact = 'compact'


class PatchApplyStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type466(Enum):
    add = 'add'


class PatchChangeKind25(BaseModel):
    type: Type466 = Field(..., title='AddPatchChangeKindType')


class Type467(Enum):
    delete = 'delete'


class PatchChangeKind26(BaseModel):
    type: Type467 = Field(..., title='DeletePatchChangeKindType')


class Type468(Enum):
    update = 'update'


class PatchChangeKind27(BaseModel):
    move_path: str | None = None
    type: Type468 = Field(..., title='UpdatePatchChangeKindType')


class PatchChangeKind(
    RootModel[PatchChangeKind25 | PatchChangeKind26 | PatchChangeKind27]
):
    root: PatchChangeKind25 | PatchChangeKind26 | PatchChangeKind27


class ReasoningEffort(Enum):
    none = 'none'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class SessionSource(Enum):
    cli = 'cli'
    vscode = 'vscode'
    exec = 'exec'
    appServer = 'appServer'
    unknown = 'unknown'


class SessionSource18(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    custom: str


class SubAgentSource13(Enum):
    review = 'review'
    compact = 'compact'
    memory_consolidation = 'memory_consolidation'


class SubAgentSource15(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    other: str


class TextElement(BaseModel):
    byteRange: ByteRange = Field(
        ...,
        description='Byte range in the parent `text` buffer that this element occupies.',
    )
    placeholder: str | None = Field(
        None,
        description='Optional human-readable placeholder for the element, displayed in the UI.',
    )


class ThreadActiveFlag(Enum):
    waitingOnApproval = 'waitingOnApproval'
    waitingOnUserInput = 'waitingOnUserInput'


class ThreadId(RootModel[str]):
    root: str


class Type469(Enum):
    userMessage = 'userMessage'


class Type470(Enum):
    hookPrompt = 'hookPrompt'


class ThreadItem(BaseModel):
    fragments: list[HookPromptFragment]
    id: str
    type: Type470 = Field(..., title='HookPromptThreadItemType')


class Type471(Enum):
    agentMessage = 'agentMessage'


class Type472(Enum):
    plan = 'plan'


class ThreadItem121(BaseModel):
    id: str
    text: str
    type: Type472 = Field(..., title='PlanThreadItemType')


class Type473(Enum):
    reasoning = 'reasoning'


class ThreadItem122(BaseModel):
    content: list[str] | None = []
    id: str
    summary: list[str] | None = []
    type: Type473 = Field(..., title='ReasoningThreadItemType')


class Type474(Enum):
    commandExecution = 'commandExecution'


class ThreadItem123(BaseModel):
    aggregatedOutput: str | None = Field(
        None, description="The command's output, aggregated from stdout and stderr."
    )
    command: str = Field(..., description='The command to be executed.')
    commandActions: list[CommandAction45] = Field(
        ...,
        description='A best-effort parsing of the command to understand the action(s) it will perform. This returns a list of CommandAction objects because a single shell command may be composed of many commands piped together.',
    )
    cwd: AbsolutePathBuf = Field(..., description="The command's working directory.")
    durationMs: int | None = Field(
        None, description='The duration of the command execution in milliseconds.'
    )
    exitCode: int | None = Field(None, description="The command's exit code.")
    id: str
    processId: str | None = Field(
        None, description='Identifier for the underlying PTY process (when available).'
    )
    source: CommandExecutionSource | None = 'agent'
    status: CommandExecutionStatus
    type: Type474 = Field(..., title='CommandExecutionThreadItemType')


class Type475(Enum):
    fileChange = 'fileChange'


class Type476(Enum):
    mcpToolCall = 'mcpToolCall'


class ThreadItem125(BaseModel):
    arguments: Any
    durationMs: int | None = Field(
        None, description='The duration of the MCP tool call in milliseconds.'
    )
    error: McpToolCallError | None = None
    id: str
    mcpAppResourceUri: str | None = None
    result: McpToolCallResult | None = None
    server: str
    status: McpToolCallStatus
    tool: str
    type: Type476 = Field(..., title='McpToolCallThreadItemType')


class Type477(Enum):
    dynamicToolCall = 'dynamicToolCall'


class ThreadItem126(BaseModel):
    arguments: Any
    contentItems: list[DynamicToolCallOutputContentItem24] | None = None
    durationMs: int | None = Field(
        None, description='The duration of the dynamic tool call in milliseconds.'
    )
    id: str
    namespace: str | None = None
    status: DynamicToolCallStatus
    success: bool | None = None
    tool: str
    type: Type477 = Field(..., title='DynamicToolCallThreadItemType')


class Type478(Enum):
    collabAgentToolCall = 'collabAgentToolCall'


class Type479(Enum):
    webSearch = 'webSearch'


class Type480(Enum):
    imageView = 'imageView'


class ThreadItem129(BaseModel):
    id: str
    path: AbsolutePathBuf
    type: Type480 = Field(..., title='ImageViewThreadItemType')


class Type481(Enum):
    imageGeneration = 'imageGeneration'


class ThreadItem130(BaseModel):
    id: str
    result: str
    revisedPrompt: str | None = None
    savedPath: AbsolutePathBuf | None = None
    status: str
    type: Type481 = Field(..., title='ImageGenerationThreadItemType')


class Type482(Enum):
    enteredReviewMode = 'enteredReviewMode'


class ThreadItem131(BaseModel):
    id: str
    review: str
    type: Type482 = Field(..., title='EnteredReviewModeThreadItemType')


class Type483(Enum):
    exitedReviewMode = 'exitedReviewMode'


class ThreadItem132(BaseModel):
    id: str
    review: str
    type: Type483 = Field(..., title='ExitedReviewModeThreadItemType')


class Type484(Enum):
    contextCompaction = 'contextCompaction'


class ThreadItem133(BaseModel):
    id: str
    type: Type484 = Field(..., title='ContextCompactionThreadItemType')


class Type485(Enum):
    notLoaded = 'notLoaded'


class ThreadStatus17(BaseModel):
    type: Type485 = Field(..., title='NotLoadedThreadStatusType')


class Type486(Enum):
    idle = 'idle'


class ThreadStatus18(BaseModel):
    type: Type486 = Field(..., title='IdleThreadStatusType')


class Type487(Enum):
    systemError = 'systemError'


class ThreadStatus19(BaseModel):
    type: Type487 = Field(..., title='SystemErrorThreadStatusType')


class Type488(Enum):
    active = 'active'


class ThreadStatus20(BaseModel):
    activeFlags: list[ThreadActiveFlag]
    type: Type488 = Field(..., title='ActiveThreadStatusType')


class ThreadStatus(
    RootModel[ThreadStatus17 | ThreadStatus18 | ThreadStatus19 | ThreadStatus20]
):
    root: ThreadStatus17 | ThreadStatus18 | ThreadStatus19 | ThreadStatus20


class TurnStatus(Enum):
    completed = 'completed'
    interrupted = 'interrupted'
    failed = 'failed'
    inProgress = 'inProgress'


class Type489(Enum):
    text = 'text'


class UserInput41(BaseModel):
    text: str
    text_elements: list[TextElement] | None = Field(
        [],
        description='UI-defined spans within `text` used to render or persist special elements.',
        validate_default=True,
    )
    type: Type489 = Field(..., title='TextUserInputType')


class Type490(Enum):
    image = 'image'


class UserInput42(BaseModel):
    type: Type490 = Field(..., title='ImageUserInputType')
    url: str


class Type491(Enum):
    localImage = 'localImage'


class UserInput43(BaseModel):
    path: str
    type: Type491 = Field(..., title='LocalImageUserInputType')


class Type492(Enum):
    skill = 'skill'


class UserInput44(BaseModel):
    name: str
    path: str
    type: Type492 = Field(..., title='SkillUserInputType')


class Type493(Enum):
    mention = 'mention'


class UserInput45(BaseModel):
    name: str
    path: str
    type: Type493 = Field(..., title='MentionUserInputType')


class UserInput(
    RootModel[UserInput41 | UserInput42 | UserInput43 | UserInput44 | UserInput45]
):
    root: UserInput41 | UserInput42 | UserInput43 | UserInput44 | UserInput45


class Type494(Enum):
    search = 'search'


class WebSearchAction29(BaseModel):
    queries: list[str] | None = None
    query: str | None = None
    type: Type494 = Field(..., title='SearchWebSearchActionType')


class Type495(Enum):
    openPage = 'openPage'


class WebSearchAction30(BaseModel):
    type: Type495 = Field(..., title='OpenPageWebSearchActionType')
    url: str | None = None


class Type496(Enum):
    findInPage = 'findInPage'


class WebSearchAction31(BaseModel):
    pattern: str | None = None
    type: Type496 = Field(..., title='FindInPageWebSearchActionType')
    url: str | None = None


class Type497(Enum):
    other = 'other'


class WebSearchAction32(BaseModel):
    type: Type497 = Field(..., title='OtherWebSearchActionType')


class WebSearchAction(
    RootModel[
        WebSearchAction29 | WebSearchAction30 | WebSearchAction31 | WebSearchAction32
    ]
):
    root: WebSearchAction29 | WebSearchAction30 | WebSearchAction31 | WebSearchAction32


class ActiveTurnNotSteerable(BaseModel):
    turnKind: NonSteerableTurnKind


class CodexErrorInfo48(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeTurnNotSteerable: ActiveTurnNotSteerable


class CodexErrorInfo42(
    RootModel[
        CodexErrorInfo
        | CodexErrorInfo44
        | CodexErrorInfo45
        | CodexErrorInfo46
        | CodexErrorInfo47
        | CodexErrorInfo48
    ]
):
    root: (
        CodexErrorInfo
        | CodexErrorInfo44
        | CodexErrorInfo45
        | CodexErrorInfo46
        | CodexErrorInfo47
        | CodexErrorInfo48
    ) = Field(
        ...,
        description='This translation layer make sure that we expose codex error code in camel case.\n\nWhen an upstream HTTP status is available (for example, from the Responses API or a provider), it is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.',
    )


class CollabAgentState(BaseModel):
    message: str | None = None
    status: CollabAgentStatus


class FileUpdateChange(BaseModel):
    diff: str
    kind: PatchChangeKind
    path: str


class MemoryCitation(BaseModel):
    entries: list[MemoryCitationEntry]
    threadIds: list[str]


class ThreadSpawn(BaseModel):
    agent_nickname: str | None = None
    agent_path: AgentPath | None = None
    agent_role: str | None = None
    depth: int
    parent_thread_id: ThreadId


class SubAgentSource14(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    thread_spawn: ThreadSpawn


class SubAgentSource(RootModel[SubAgentSource13 | SubAgentSource14 | SubAgentSource15]):
    root: SubAgentSource13 | SubAgentSource14 | SubAgentSource15


class ThreadItem118(BaseModel):
    content: list[UserInput]
    id: str
    type: Type469 = Field(..., title='UserMessageThreadItemType')


class ThreadItem120(BaseModel):
    id: str
    memoryCitation: MemoryCitation | None = None
    phase: MessagePhase27 | None = None
    text: str
    type: Type471 = Field(..., title='AgentMessageThreadItemType')


class ThreadItem124(BaseModel):
    changes: list[FileUpdateChange]
    id: str
    status: PatchApplyStatus
    type: Type475 = Field(..., title='FileChangeThreadItemType')


class ThreadItem127(BaseModel):
    agentsStates: dict[str, CollabAgentState] = Field(
        ..., description='Last known status of the target agents, when available.'
    )
    id: str = Field(..., description='Unique identifier for this collab tool call.')
    model: str | None = Field(
        None, description='Model requested for the spawned agent, when applicable.'
    )
    prompt: str | None = Field(
        None,
        description='Prompt text sent as part of the collab tool call, when available.',
    )
    reasoningEffort: ReasoningEffort | None = Field(
        None,
        description='Reasoning effort requested for the spawned agent, when applicable.',
    )
    receiverThreadIds: list[str] = Field(
        ...,
        description='Thread ID of the receiving agent, when applicable. In case of spawn operation, this corresponds to the newly spawned agent.',
    )
    senderThreadId: str = Field(
        ..., description='Thread ID of the agent issuing the collab request.'
    )
    status: CollabAgentToolCallStatus = Field(
        ..., description='Current status of the collab tool call.'
    )
    tool: CollabAgentTool = Field(
        ..., description='Name of the collab tool that was invoked.'
    )
    type: Type478 = Field(..., title='CollabAgentToolCallThreadItemType')


class ThreadItem128(BaseModel):
    action: WebSearchAction | None = None
    id: str
    query: str
    type: Type479 = Field(..., title='WebSearchThreadItemType')


class ThreadItem117(
    RootModel[
        ThreadItem118
        | ThreadItem
        | ThreadItem120
        | ThreadItem121
        | ThreadItem122
        | ThreadItem123
        | ThreadItem124
        | ThreadItem125
        | ThreadItem126
        | ThreadItem127
        | ThreadItem128
        | ThreadItem129
        | ThreadItem130
        | ThreadItem131
        | ThreadItem132
        | ThreadItem133
    ]
):
    root: (
        ThreadItem118
        | ThreadItem
        | ThreadItem120
        | ThreadItem121
        | ThreadItem122
        | ThreadItem123
        | ThreadItem124
        | ThreadItem125
        | ThreadItem126
        | ThreadItem127
        | ThreadItem128
        | ThreadItem129
        | ThreadItem130
        | ThreadItem131
        | ThreadItem132
        | ThreadItem133
    )


class TurnError(BaseModel):
    additionalDetails: str | None = None
    codexErrorInfo: CodexErrorInfo42 | None = None
    message: str


class SessionSource19(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subAgent: SubAgentSource


class SessionSource16(RootModel[SessionSource | SessionSource18 | SessionSource19]):
    root: SessionSource | SessionSource18 | SessionSource19


class Turn(BaseModel):
    completedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn completed.'
    )
    durationMs: int | None = Field(
        None,
        description='Duration between turn start and completion in milliseconds, if known.',
    )
    error: TurnError | None = Field(
        None, description="Only populated when the Turn's status is failed."
    )
    id: str
    items: list[ThreadItem117] = Field(
        ...,
        description='Only populated on a `thread/resume` or `thread/fork` response. For all other responses and notifications returning a Turn, the items field will be an empty list.',
    )
    startedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn started.'
    )
    status: TurnStatus


class Thread(BaseModel):
    agentNickname: str | None = Field(
        None,
        description='Optional random unique nickname assigned to an AgentControl-spawned sub-agent.',
    )
    agentRole: str | None = Field(
        None,
        description='Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.',
    )
    cliVersion: str = Field(
        ..., description='Version of the CLI that created the thread.'
    )
    createdAt: int = Field(
        ..., description='Unix timestamp (in seconds) when the thread was created.'
    )
    cwd: AbsolutePathBuf = Field(
        ..., description='Working directory captured for the thread.'
    )
    ephemeral: bool = Field(
        ...,
        description='Whether the thread is ephemeral and should not be materialized on disk.',
    )
    forkedFromId: str | None = Field(
        None,
        description='Source thread id when this thread was created by forking another thread.',
    )
    gitInfo: GitInfo | None = Field(
        None, description='Optional Git metadata captured when the thread was created.'
    )
    id: str
    modelProvider: str = Field(
        ..., description="Model provider used for this thread (for example, 'openai')."
    )
    name: str | None = Field(None, description='Optional user-facing thread title.')
    path: str | None = Field(None, description='[UNSTABLE] Path to the thread on disk.')
    preview: str = Field(
        ..., description='Usually the first user message in the thread, if available.'
    )
    source: SessionSource16 = Field(
        ...,
        description='Origin of the thread (CLI, VSCode, codex exec, codex app-server, etc.).',
    )
    status: ThreadStatus = Field(
        ..., description='Current runtime status for the thread.'
    )
    turns: list[Turn] = Field(
        ...,
        description='Only populated on `thread/resume`, `thread/rollback`, `thread/fork`, and `thread/read` (when `includeTurns` is true) responses. For all other responses and notifications returning a Thread, the turns field will be an empty list.',
    )
    updatedAt: int = Field(
        ..., description='Unix timestamp (in seconds) when the thread was last updated.'
    )


class ThreadReadResponse(BaseModel):
    thread: Thread
