# generated by datamodel-codegen:
#   filename:  v2/ThreadInjectItemsParams.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ThreadInjectItemsParams(BaseModel):
    items: list[Any] = Field(
        ...,
        description="Raw Responses API items to append to the thread's model-visible history.",
    )
    threadId: str
