# generated by datamodel-codegen:
#   filename:  v2/TurnPlanUpdatedNotification.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class TurnPlanStepStatus(Enum):
    pending = 'pending'
    inProgress = 'inProgress'
    completed = 'completed'


class TurnPlanStep(BaseModel):
    status: TurnPlanStepStatus
    step: str


class TurnPlanUpdatedNotification(BaseModel):
    explanation: str | None = None
    plan: list[TurnPlanStep]
    threadId: str
    turnId: str
