# generated by datamodel-codegen:
#   filename:  v2/WarningNotification.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class WarningNotification(BaseModel):
    message: str = Field(..., description='Concise warning message for the user.')
    threadId: str | None = Field(
        None,
        description='Optional thread target when the warning applies to a specific thread.',
    )
