# generated by datamodel-codegen:
#   filename:  ServerNotification.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class Method(Enum):
    error = 'error'


class Method72(Enum):
    thread_started = 'thread/started'


class Method73(Enum):
    thread_status_changed = 'thread/status/changed'


class Method74(Enum):
    thread_archived = 'thread/archived'


class Method75(Enum):
    thread_unarchived = 'thread/unarchived'


class Method76(Enum):
    thread_closed = 'thread/closed'


class Method77(Enum):
    skills_changed = 'skills/changed'


class Method78(Enum):
    thread_name_updated = 'thread/name/updated'


class Method79(Enum):
    thread_tokenUsage_updated = 'thread/tokenUsage/updated'


class Method80(Enum):
    turn_started = 'turn/started'


class Method81(Enum):
    hook_started = 'hook/started'


class Method82(Enum):
    turn_completed = 'turn/completed'


class Method83(Enum):
    hook_completed = 'hook/completed'


class Method84(Enum):
    turn_diff_updated = 'turn/diff/updated'


class Method85(Enum):
    turn_plan_updated = 'turn/plan/updated'


class Method86(Enum):
    item_started = 'item/started'


class Method87(Enum):
    item_autoApprovalReview_started = 'item/autoApprovalReview/started'


class Method88(Enum):
    item_autoApprovalReview_completed = 'item/autoApprovalReview/completed'


class Method89(Enum):
    item_completed = 'item/completed'


class Method90(Enum):
    item_agentMessage_delta = 'item/agentMessage/delta'


class Method91(Enum):
    item_plan_delta = 'item/plan/delta'


class Method92(Enum):
    command_exec_outputDelta = 'command/exec/outputDelta'


class Method93(Enum):
    item_commandExecution_outputDelta = 'item/commandExecution/outputDelta'


class Method94(Enum):
    item_commandExecution_terminalInteraction = (
        'item/commandExecution/terminalInteraction'
    )


class Method95(Enum):
    item_fileChange_outputDelta = 'item/fileChange/outputDelta'


class Method96(Enum):
    item_fileChange_patchUpdated = 'item/fileChange/patchUpdated'


class Method97(Enum):
    serverRequest_resolved = 'serverRequest/resolved'


class Method98(Enum):
    item_mcpToolCall_progress = 'item/mcpToolCall/progress'


class Method99(Enum):
    mcpServer_oauthLogin_completed = 'mcpServer/oauthLogin/completed'


class Method100(Enum):
    mcpServer_startupStatus_updated = 'mcpServer/startupStatus/updated'


class Method101(Enum):
    account_updated = 'account/updated'


class Method102(Enum):
    account_rateLimits_updated = 'account/rateLimits/updated'


class Method103(Enum):
    app_list_updated = 'app/list/updated'


class Method104(Enum):
    externalAgentConfig_import_completed = 'externalAgentConfig/import/completed'


class Method105(Enum):
    fs_changed = 'fs/changed'


class Method106(Enum):
    item_reasoning_summaryTextDelta = 'item/reasoning/summaryTextDelta'


class Method107(Enum):
    item_reasoning_summaryPartAdded = 'item/reasoning/summaryPartAdded'


class Method108(Enum):
    item_reasoning_textDelta = 'item/reasoning/textDelta'


class Method109(Enum):
    thread_compacted = 'thread/compacted'


class Method110(Enum):
    model_rerouted = 'model/rerouted'


class Method111(Enum):
    model_verification = 'model/verification'


class Method112(Enum):
    warning = 'warning'


class Method113(Enum):
    guardianWarning = 'guardianWarning'


class Method114(Enum):
    deprecationNotice = 'deprecationNotice'


class Method115(Enum):
    configWarning = 'configWarning'


class Method116(Enum):
    fuzzyFileSearch_sessionUpdated = 'fuzzyFileSearch/sessionUpdated'


class Method117(Enum):
    fuzzyFileSearch_sessionCompleted = 'fuzzyFileSearch/sessionCompleted'


class Method118(Enum):
    thread_realtime_started = 'thread/realtime/started'


class Method119(Enum):
    thread_realtime_itemAdded = 'thread/realtime/itemAdded'


class Method120(Enum):
    thread_realtime_transcript_delta = 'thread/realtime/transcript/delta'


class Method121(Enum):
    thread_realtime_transcript_done = 'thread/realtime/transcript/done'


class Method122(Enum):
    thread_realtime_outputAudio_delta = 'thread/realtime/outputAudio/delta'


class Method123(Enum):
    thread_realtime_sdp = 'thread/realtime/sdp'


class Method124(Enum):
    thread_realtime_error = 'thread/realtime/error'


class Method125(Enum):
    thread_realtime_closed = 'thread/realtime/closed'


class Method126(Enum):
    windows_worldWritableWarning = 'windows/worldWritableWarning'


class Method127(Enum):
    windowsSandbox_setupCompleted = 'windowsSandbox/setupCompleted'


class Method128(Enum):
    account_login_completed = 'account/login/completed'


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class AccountLoginCompletedNotification(BaseModel):
    error: str | None = None
    loginId: str | None = None
    success: bool


class AdditionalNetworkPermissions(BaseModel):
    enabled: bool | None = None


class AgentMessageDeltaNotification(BaseModel):
    delta: str
    itemId: str
    threadId: str
    turnId: str


class AgentPath(RootModel[str]):
    root: str


class AppBranding(BaseModel):
    category: str | None = None
    developer: str | None = None
    isDiscoverableApp: bool
    privacyPolicy: str | None = None
    termsOfService: str | None = None
    website: str | None = None


class AppReview(BaseModel):
    status: str


class AppScreenshot(BaseModel):
    fileId: str | None = None
    url: str | None = None
    userPrompt: str


class AuthMode5(Enum):
    apikey = 'apikey'


class AuthMode6(Enum):
    chatgpt = 'chatgpt'


class AuthMode7(Enum):
    chatgptAuthTokens = 'chatgptAuthTokens'


class AuthMode8(Enum):
    agentIdentity = 'agentIdentity'


class AuthMode(RootModel[AuthMode5 | AuthMode6 | AuthMode7 | AuthMode8]):
    root: AuthMode5 | AuthMode6 | AuthMode7 | AuthMode8 = Field(
        ..., description='Authentication mode for OpenAI-backed providers.'
    )


class AutoReviewDecisionSource(Enum):
    agent = 'agent'


class ByteRange(BaseModel):
    end: conint(ge=0)
    start: conint(ge=0)


class CodexErrorInfo(Enum):
    contextWindowExceeded = 'contextWindowExceeded'
    usageLimitExceeded = 'usageLimitExceeded'
    serverOverloaded = 'serverOverloaded'
    cyberPolicy = 'cyberPolicy'
    internalServerError = 'internalServerError'
    unauthorized = 'unauthorized'
    badRequest = 'badRequest'
    threadRollbackFailed = 'threadRollbackFailed'
    sandboxError = 'sandboxError'
    other = 'other'


class HttpConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo16(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    httpConnectionFailed: HttpConnectionFailed


class ResponseStreamConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo17(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamConnectionFailed: ResponseStreamConnectionFailed


class ResponseStreamDisconnected(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo18(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamDisconnected: ResponseStreamDisconnected


class ResponseTooManyFailedAttempts(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo19(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseTooManyFailedAttempts: ResponseTooManyFailedAttempts


class CollabAgentStatus(Enum):
    pendingInit = 'pendingInit'
    running = 'running'
    interrupted = 'interrupted'
    completed = 'completed'
    errored = 'errored'
    shutdown = 'shutdown'
    notFound = 'notFound'


class CollabAgentTool(Enum):
    spawnAgent = 'spawnAgent'
    sendInput = 'sendInput'
    resumeAgent = 'resumeAgent'
    wait = 'wait'
    closeAgent = 'closeAgent'


class CollabAgentToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class Type(Enum):
    read = 'read'


class CommandAction(BaseModel):
    command: str
    name: str
    path: AbsolutePathBuf
    type: Type = Field(..., title='ReadCommandActionType')


class Type274(Enum):
    listFiles = 'listFiles'


class CommandAction22(BaseModel):
    command: str
    path: str | None = None
    type: Type274 = Field(..., title='ListFilesCommandActionType')


class Type275(Enum):
    search = 'search'


class CommandAction23(BaseModel):
    command: str
    path: str | None = None
    query: str | None = None
    type: Type275 = Field(..., title='SearchCommandActionType')


class Type276(Enum):
    unknown = 'unknown'


class CommandAction24(BaseModel):
    command: str
    type: Type276 = Field(..., title='UnknownCommandActionType')


class CommandAction20(
    RootModel[CommandAction | CommandAction22 | CommandAction23 | CommandAction24]
):
    root: CommandAction | CommandAction22 | CommandAction23 | CommandAction24


class CommandExecOutputStream3(Enum):
    stdout = 'stdout'


class CommandExecOutputStream4(Enum):
    stderr = 'stderr'


class CommandExecOutputStream(
    RootModel[CommandExecOutputStream3 | CommandExecOutputStream4]
):
    root: CommandExecOutputStream3 | CommandExecOutputStream4 = Field(
        ..., description='Stream label for `command/exec/outputDelta` notifications.'
    )


class CommandExecutionOutputDeltaNotification(BaseModel):
    delta: str
    itemId: str
    threadId: str
    turnId: str


class CommandExecutionSource(Enum):
    agent = 'agent'
    userShell = 'userShell'
    unifiedExecStartup = 'unifiedExecStartup'
    unifiedExecInteraction = 'unifiedExecInteraction'


class CommandExecutionStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class ContextCompactedNotification(BaseModel):
    threadId: str
    turnId: str


class CreditsSnapshot(BaseModel):
    balance: str | None = None
    hasCredits: bool
    unlimited: bool


class DeprecationNoticeNotification(BaseModel):
    details: str | None = Field(
        None,
        description='Optional extra guidance, such as migration steps or rationale.',
    )
    summary: str = Field(..., description='Concise summary of what is deprecated.')


class Type277(Enum):
    inputText = 'inputText'


class DynamicToolCallOutputContentItem(BaseModel):
    text: str
    type: Type277 = Field(..., title='InputTextDynamicToolCallOutputContentItemType')


class Type278(Enum):
    inputImage = 'inputImage'


class DynamicToolCallOutputContentItem14(BaseModel):
    imageUrl: str
    type: Type278 = Field(..., title='InputImageDynamicToolCallOutputContentItemType')


class DynamicToolCallOutputContentItem12(
    RootModel[DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem14]
):
    root: DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem14


class DynamicToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class ExternalAgentConfigImportCompletedNotification(BaseModel):
    pass


class FileChangeOutputDeltaNotification(BaseModel):
    delta: str
    itemId: str
    threadId: str
    turnId: str


class FileSystemAccessMode(Enum):
    read = 'read'
    write = 'write'
    none = 'none'


class Type279(Enum):
    path = 'path'


class FileSystemPath(BaseModel):
    path: AbsolutePathBuf
    type: Type279 = Field(..., title='PathFileSystemPathType')


class Type280(Enum):
    glob_pattern = 'glob_pattern'


class FileSystemPath30(BaseModel):
    pattern: str
    type: Type280 = Field(..., title='GlobPatternFileSystemPathType')


class Type281(Enum):
    special = 'special'


class Kind(Enum):
    root = 'root'


class FileSystemSpecialPath50(BaseModel):
    kind: Kind


class Kind50(Enum):
    minimal = 'minimal'


class FileSystemSpecialPath51(BaseModel):
    kind: Kind50


class Kind51(Enum):
    current_working_directory = 'current_working_directory'


class FileSystemSpecialPath52(BaseModel):
    kind: Kind51


class Kind52(Enum):
    project_roots = 'project_roots'


class FileSystemSpecialPath53(BaseModel):
    kind: Kind52
    subpath: str | None = None


class Kind53(Enum):
    tmpdir = 'tmpdir'


class FileSystemSpecialPath54(BaseModel):
    kind: Kind53


class Kind54(Enum):
    slash_tmp = 'slash_tmp'


class FileSystemSpecialPath55(BaseModel):
    kind: Kind54


class Kind55(Enum):
    unknown = 'unknown'


class FileSystemSpecialPath56(BaseModel):
    kind: Kind55
    path: str
    subpath: str | None = None


class FileSystemSpecialPath(
    RootModel[
        FileSystemSpecialPath50
        | FileSystemSpecialPath51
        | FileSystemSpecialPath52
        | FileSystemSpecialPath53
        | FileSystemSpecialPath54
        | FileSystemSpecialPath55
        | FileSystemSpecialPath56
    ]
):
    root: (
        FileSystemSpecialPath50
        | FileSystemSpecialPath51
        | FileSystemSpecialPath52
        | FileSystemSpecialPath53
        | FileSystemSpecialPath54
        | FileSystemSpecialPath55
        | FileSystemSpecialPath56
    )


class FsChangedNotification(BaseModel):
    changedPaths: list[AbsolutePathBuf] = Field(
        ..., description='File or directory paths associated with this event.'
    )
    watchId: str = Field(
        ..., description='Watch identifier previously provided to `fs/watch`.'
    )


class FuzzyFileSearchMatchType(Enum):
    file = 'file'
    directory = 'directory'


class FuzzyFileSearchResult(BaseModel):
    file_name: str
    indices: list[conint(ge=0)] | None = None
    match_type: FuzzyFileSearchMatchType
    path: str
    root: str
    score: conint(ge=0)


class FuzzyFileSearchSessionCompletedNotification(BaseModel):
    sessionId: str


class FuzzyFileSearchSessionUpdatedNotification(BaseModel):
    files: list[FuzzyFileSearchResult]
    query: str
    sessionId: str


class GitInfo(BaseModel):
    branch: str | None = None
    originUrl: str | None = None
    sha: str | None = None


class Type282(Enum):
    command = 'command'


class Type283(Enum):
    execve = 'execve'


class Type284(Enum):
    applyPatch = 'applyPatch'


class GuardianApprovalReviewAction(BaseModel):
    cwd: AbsolutePathBuf
    files: list[AbsolutePathBuf]
    type: Type284 = Field(..., title='ApplyPatchGuardianApprovalReviewActionType')


class Type285(Enum):
    networkAccess = 'networkAccess'


class Type286(Enum):
    mcpToolCall = 'mcpToolCall'


class GuardianApprovalReviewAction18(BaseModel):
    connectorId: str | None = None
    connectorName: str | None = None
    server: str
    toolName: str
    toolTitle: str | None = None
    type: Type286 = Field(..., title='McpToolCallGuardianApprovalReviewActionType')


class Type287(Enum):
    requestPermissions = 'requestPermissions'


class GuardianApprovalReviewStatus(Enum):
    inProgress = 'inProgress'
    approved = 'approved'
    denied = 'denied'
    timedOut = 'timedOut'
    aborted = 'aborted'


class GuardianCommandSource(Enum):
    shell = 'shell'
    unifiedExec = 'unifiedExec'


class GuardianRiskLevel(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class GuardianUserAuthorization(Enum):
    unknown = 'unknown'
    low = 'low'
    medium = 'medium'
    high = 'high'


class GuardianWarningNotification(BaseModel):
    message: str = Field(
        ..., description='Concise guardian warning message for the user.'
    )
    threadId: str = Field(..., description='Thread target for the guardian warning.')


class HookEventName(Enum):
    preToolUse = 'preToolUse'
    permissionRequest = 'permissionRequest'
    postToolUse = 'postToolUse'
    sessionStart = 'sessionStart'
    userPromptSubmit = 'userPromptSubmit'
    stop = 'stop'


class HookExecutionMode(Enum):
    sync = 'sync'
    async_ = 'async'


class HookHandlerType(Enum):
    command = 'command'
    prompt = 'prompt'
    agent = 'agent'


class HookOutputEntryKind(Enum):
    warning = 'warning'
    stop = 'stop'
    feedback = 'feedback'
    context = 'context'
    error = 'error'


class HookPromptFragment(BaseModel):
    hookRunId: str
    text: str


class HookRunStatus(Enum):
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    blocked = 'blocked'
    stopped = 'stopped'


class HookScope(Enum):
    thread = 'thread'
    turn = 'turn'


class HookSource(Enum):
    system = 'system'
    user = 'user'
    project = 'project'
    mdm = 'mdm'
    sessionFlags = 'sessionFlags'
    legacyManagedConfigFile = 'legacyManagedConfigFile'
    legacyManagedConfigMdm = 'legacyManagedConfigMdm'
    unknown = 'unknown'


class McpServerOauthLoginCompletedNotification(BaseModel):
    error: str | None = None
    name: str
    success: bool


class McpServerStartupState(Enum):
    starting = 'starting'
    ready = 'ready'
    failed = 'failed'
    cancelled = 'cancelled'


class McpServerStatusUpdatedNotification(BaseModel):
    error: str | None = None
    name: str
    status: McpServerStartupState


class McpToolCallError(BaseModel):
    message: str


class McpToolCallProgressNotification(BaseModel):
    itemId: str
    message: str
    threadId: str
    turnId: str


class McpToolCallResult(BaseModel):
    field_meta: Any | None = Field(None, alias='_meta')
    content: list[Any]
    structuredContent: Any | None = None


class McpToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class MemoryCitationEntry(BaseModel):
    lineEnd: conint(ge=0)
    lineStart: conint(ge=0)
    note: str
    path: str


class MessagePhase(Enum):
    commentary = 'commentary'


class MessagePhase17(Enum):
    final_answer = 'final_answer'


class MessagePhase15(RootModel[MessagePhase | MessagePhase17]):
    root: MessagePhase | MessagePhase17 = Field(
        ...,
        description='Classifies an assistant message as interim commentary or final answer text.\n\nProviders do not emit this consistently, so callers must treat `None` as "phase unknown" and keep compatibility behavior for legacy models.',
    )


class ModelRerouteReason(Enum):
    highRiskCyberActivity = 'highRiskCyberActivity'


class ModelReroutedNotification(BaseModel):
    fromModel: str
    reason: ModelRerouteReason
    threadId: str
    toModel: str
    turnId: str


class ModelVerification(Enum):
    trustedAccessForCyber = 'trustedAccessForCyber'


class ModelVerificationNotification(BaseModel):
    threadId: str
    turnId: str
    verifications: list[ModelVerification]


class NetworkApprovalProtocol(Enum):
    http = 'http'
    https = 'https'
    socks5Tcp = 'socks5Tcp'
    socks5Udp = 'socks5Udp'


class NonSteerableTurnKind(Enum):
    review = 'review'
    compact = 'compact'


class PatchApplyStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type288(Enum):
    add = 'add'


class PatchChangeKind13(BaseModel):
    type: Type288 = Field(..., title='AddPatchChangeKindType')


class Type289(Enum):
    delete = 'delete'


class PatchChangeKind14(BaseModel):
    type: Type289 = Field(..., title='DeletePatchChangeKindType')


class Type290(Enum):
    update = 'update'


class PatchChangeKind15(BaseModel):
    move_path: str | None = None
    type: Type290 = Field(..., title='UpdatePatchChangeKindType')


class PatchChangeKind(
    RootModel[PatchChangeKind13 | PatchChangeKind14 | PatchChangeKind15]
):
    root: PatchChangeKind13 | PatchChangeKind14 | PatchChangeKind15


class PlanDeltaNotification(BaseModel):
    delta: str
    itemId: str
    threadId: str
    turnId: str


class PlanType(Enum):
    free = 'free'
    go = 'go'
    plus = 'plus'
    pro = 'pro'
    prolite = 'prolite'
    team = 'team'
    self_serve_business_usage_based = 'self_serve_business_usage_based'
    business = 'business'
    enterprise_cbp_usage_based = 'enterprise_cbp_usage_based'
    enterprise = 'enterprise'
    edu = 'edu'
    unknown = 'unknown'


class RateLimitReachedType(Enum):
    rate_limit_reached = 'rate_limit_reached'
    workspace_owner_credits_depleted = 'workspace_owner_credits_depleted'
    workspace_member_credits_depleted = 'workspace_member_credits_depleted'
    workspace_owner_usage_limit_reached = 'workspace_owner_usage_limit_reached'
    workspace_member_usage_limit_reached = 'workspace_member_usage_limit_reached'


class RateLimitWindow(BaseModel):
    resetsAt: int | None = None
    usedPercent: int
    windowDurationMins: int | None = None


class RealtimeConversationVersion(Enum):
    v1 = 'v1'
    v2 = 'v2'


class ReasoningEffort(Enum):
    none = 'none'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class ReasoningSummaryPartAddedNotification(BaseModel):
    itemId: str
    summaryIndex: int
    threadId: str
    turnId: str


class ReasoningSummaryTextDeltaNotification(BaseModel):
    delta: str
    itemId: str
    summaryIndex: int
    threadId: str
    turnId: str


class ReasoningTextDeltaNotification(BaseModel):
    contentIndex: int
    delta: str
    itemId: str
    threadId: str
    turnId: str


class RequestId(RootModel[str | int]):
    root: str | int


class ServerRequestResolvedNotification(BaseModel):
    requestId: RequestId
    threadId: str


class SessionSource1(Enum):
    cli = 'cli'
    vscode = 'vscode'
    exec = 'exec'
    appServer = 'appServer'
    unknown = 'unknown'


class SessionSource2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    custom: str


class SkillsChangedNotification(BaseModel):
    pass


class SubAgentSource1(Enum):
    review = 'review'
    compact = 'compact'
    memory_consolidation = 'memory_consolidation'


class SubAgentSource3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    other: str


class TerminalInteractionNotification(BaseModel):
    itemId: str
    processId: str
    stdin: str
    threadId: str
    turnId: str


class TextElement(BaseModel):
    byteRange: ByteRange = Field(
        ...,
        description='Byte range in the parent `text` buffer that this element occupies.',
    )
    placeholder: str | None = Field(
        None,
        description='Optional human-readable placeholder for the element, displayed in the UI.',
    )


class TextPosition(BaseModel):
    column: conint(ge=0) = Field(
        ..., description='1-based column number (in Unicode scalar values).'
    )
    line: conint(ge=0) = Field(..., description='1-based line number.')


class TextRange(BaseModel):
    end: TextPosition
    start: TextPosition


class ThreadActiveFlag(Enum):
    waitingOnApproval = 'waitingOnApproval'
    waitingOnUserInput = 'waitingOnUserInput'


class ThreadArchivedNotification(BaseModel):
    threadId: str


class ThreadClosedNotification(BaseModel):
    threadId: str


class ThreadId(RootModel[str]):
    root: str


class Type291(Enum):
    userMessage = 'userMessage'


class Type292(Enum):
    hookPrompt = 'hookPrompt'


class ThreadItem51(BaseModel):
    fragments: list[HookPromptFragment]
    id: str
    type: Type292 = Field(..., title='HookPromptThreadItemType')


class Type293(Enum):
    agentMessage = 'agentMessage'


class Type294(Enum):
    plan = 'plan'


class ThreadItem53(BaseModel):
    id: str
    text: str
    type: Type294 = Field(..., title='PlanThreadItemType')


class Type295(Enum):
    reasoning = 'reasoning'


class ThreadItem54(BaseModel):
    content: list[str] | None = []
    id: str
    summary: list[str] | None = []
    type: Type295 = Field(..., title='ReasoningThreadItemType')


class Type296(Enum):
    commandExecution = 'commandExecution'


class ThreadItem55(BaseModel):
    aggregatedOutput: str | None = Field(
        None, description="The command's output, aggregated from stdout and stderr."
    )
    command: str = Field(..., description='The command to be executed.')
    commandActions: list[CommandAction20] = Field(
        ...,
        description='A best-effort parsing of the command to understand the action(s) it will perform. This returns a list of CommandAction objects because a single shell command may be composed of many commands piped together.',
    )
    cwd: AbsolutePathBuf = Field(..., description="The command's working directory.")
    durationMs: int | None = Field(
        None, description='The duration of the command execution in milliseconds.'
    )
    exitCode: int | None = Field(None, description="The command's exit code.")
    id: str
    processId: str | None = Field(
        None, description='Identifier for the underlying PTY process (when available).'
    )
    source: CommandExecutionSource | None = 'agent'
    status: CommandExecutionStatus
    type: Type296 = Field(..., title='CommandExecutionThreadItemType')


class Type297(Enum):
    fileChange = 'fileChange'


class Type298(Enum):
    mcpToolCall = 'mcpToolCall'


class ThreadItem57(BaseModel):
    arguments: Any
    durationMs: int | None = Field(
        None, description='The duration of the MCP tool call in milliseconds.'
    )
    error: McpToolCallError | None = None
    id: str
    mcpAppResourceUri: str | None = None
    result: McpToolCallResult | None = None
    server: str
    status: McpToolCallStatus
    tool: str
    type: Type298 = Field(..., title='McpToolCallThreadItemType')


class Type299(Enum):
    dynamicToolCall = 'dynamicToolCall'


class ThreadItem58(BaseModel):
    arguments: Any
    contentItems: list[DynamicToolCallOutputContentItem12] | None = None
    durationMs: int | None = Field(
        None, description='The duration of the dynamic tool call in milliseconds.'
    )
    id: str
    namespace: str | None = None
    status: DynamicToolCallStatus
    success: bool | None = None
    tool: str
    type: Type299 = Field(..., title='DynamicToolCallThreadItemType')


class Type300(Enum):
    collabAgentToolCall = 'collabAgentToolCall'


class Type301(Enum):
    webSearch = 'webSearch'


class Type302(Enum):
    imageView = 'imageView'


class ThreadItem61(BaseModel):
    id: str
    path: AbsolutePathBuf
    type: Type302 = Field(..., title='ImageViewThreadItemType')


class Type303(Enum):
    imageGeneration = 'imageGeneration'


class ThreadItem62(BaseModel):
    id: str
    result: str
    revisedPrompt: str | None = None
    savedPath: AbsolutePathBuf | None = None
    status: str
    type: Type303 = Field(..., title='ImageGenerationThreadItemType')


class Type304(Enum):
    enteredReviewMode = 'enteredReviewMode'


class ThreadItem63(BaseModel):
    id: str
    review: str
    type: Type304 = Field(..., title='EnteredReviewModeThreadItemType')


class Type305(Enum):
    exitedReviewMode = 'exitedReviewMode'


class ThreadItem64(BaseModel):
    id: str
    review: str
    type: Type305 = Field(..., title='ExitedReviewModeThreadItemType')


class Type306(Enum):
    contextCompaction = 'contextCompaction'


class ThreadItem65(BaseModel):
    id: str
    type: Type306 = Field(..., title='ContextCompactionThreadItemType')


class ThreadNameUpdatedNotification(BaseModel):
    threadId: str
    threadName: str | None = None


class ThreadRealtimeAudioChunk(BaseModel):
    data: str
    itemId: str | None = None
    numChannels: conint(ge=0)
    sampleRate: conint(ge=0)
    samplesPerChannel: conint(ge=0) | None = None


class ThreadRealtimeClosedNotification(BaseModel):
    reason: str | None = None
    threadId: str


class ThreadRealtimeErrorNotification(BaseModel):
    message: str
    threadId: str


class ThreadRealtimeItemAddedNotification(BaseModel):
    item: Any
    threadId: str


class ThreadRealtimeOutputAudioDeltaNotification(BaseModel):
    audio: ThreadRealtimeAudioChunk
    threadId: str


class ThreadRealtimeSdpNotification(BaseModel):
    sdp: str
    threadId: str


class ThreadRealtimeStartedNotification(BaseModel):
    sessionId: str | None = None
    threadId: str
    version: RealtimeConversationVersion


class ThreadRealtimeTranscriptDeltaNotification(BaseModel):
    delta: str = Field(
        ..., description='Live transcript delta from the realtime event.'
    )
    role: str
    threadId: str


class ThreadRealtimeTranscriptDoneNotification(BaseModel):
    role: str
    text: str = Field(..., description='Final complete text for the transcript part.')
    threadId: str


class Type307(Enum):
    notLoaded = 'notLoaded'


class ThreadStatus1(BaseModel):
    type: Type307 = Field(..., title='NotLoadedThreadStatusType')


class Type308(Enum):
    idle = 'idle'


class ThreadStatus2(BaseModel):
    type: Type308 = Field(..., title='IdleThreadStatusType')


class Type309(Enum):
    systemError = 'systemError'


class ThreadStatus3(BaseModel):
    type: Type309 = Field(..., title='SystemErrorThreadStatusType')


class Type310(Enum):
    active = 'active'


class ThreadStatus4(BaseModel):
    activeFlags: list[ThreadActiveFlag]
    type: Type310 = Field(..., title='ActiveThreadStatusType')


class ThreadStatus(
    RootModel[ThreadStatus1 | ThreadStatus2 | ThreadStatus3 | ThreadStatus4]
):
    root: ThreadStatus1 | ThreadStatus2 | ThreadStatus3 | ThreadStatus4


class ThreadStatusChangedNotification(BaseModel):
    status: ThreadStatus
    threadId: str


class ThreadUnarchivedNotification(BaseModel):
    threadId: str


class TokenUsageBreakdown(BaseModel):
    cachedInputTokens: int
    inputTokens: int
    outputTokens: int
    reasoningOutputTokens: int
    totalTokens: int


class TurnDiffUpdatedNotification(BaseModel):
    diff: str
    threadId: str
    turnId: str


class TurnPlanStepStatus(Enum):
    pending = 'pending'
    inProgress = 'inProgress'
    completed = 'completed'


class TurnStatus(Enum):
    completed = 'completed'
    interrupted = 'interrupted'
    failed = 'failed'
    inProgress = 'inProgress'


class Type311(Enum):
    text = 'text'


class UserInput21(BaseModel):
    text: str
    text_elements: list[TextElement] | None = Field(
        [],
        description='UI-defined spans within `text` used to render or persist special elements.',
        validate_default=True,
    )
    type: Type311 = Field(..., title='TextUserInputType')


class Type312(Enum):
    image = 'image'


class UserInput22(BaseModel):
    type: Type312 = Field(..., title='ImageUserInputType')
    url: str


class Type313(Enum):
    localImage = 'localImage'


class UserInput23(BaseModel):
    path: str
    type: Type313 = Field(..., title='LocalImageUserInputType')


class Type314(Enum):
    skill = 'skill'


class UserInput24(BaseModel):
    name: str
    path: str
    type: Type314 = Field(..., title='SkillUserInputType')


class Type315(Enum):
    mention = 'mention'


class UserInput25(BaseModel):
    name: str
    path: str
    type: Type315 = Field(..., title='MentionUserInputType')


class UserInput(
    RootModel[UserInput21 | UserInput22 | UserInput23 | UserInput24 | UserInput25]
):
    root: UserInput21 | UserInput22 | UserInput23 | UserInput24 | UserInput25


class WarningNotification(BaseModel):
    message: str = Field(..., description='Concise warning message for the user.')
    threadId: str | None = Field(
        None,
        description='Optional thread target when the warning applies to a specific thread.',
    )


class Type316(Enum):
    search = 'search'


class WebSearchAction13(BaseModel):
    queries: list[str] | None = None
    query: str | None = None
    type: Type316 = Field(..., title='SearchWebSearchActionType')


class Type317(Enum):
    openPage = 'openPage'


class WebSearchAction14(BaseModel):
    type: Type317 = Field(..., title='OpenPageWebSearchActionType')
    url: str | None = None


class Type318(Enum):
    findInPage = 'findInPage'


class WebSearchAction15(BaseModel):
    pattern: str | None = None
    type: Type318 = Field(..., title='FindInPageWebSearchActionType')
    url: str | None = None


class Type319(Enum):
    other = 'other'


class WebSearchAction16(BaseModel):
    type: Type319 = Field(..., title='OtherWebSearchActionType')


class WebSearchAction(
    RootModel[
        WebSearchAction13 | WebSearchAction14 | WebSearchAction15 | WebSearchAction16
    ]
):
    root: WebSearchAction13 | WebSearchAction14 | WebSearchAction15 | WebSearchAction16


class WindowsSandboxSetupMode(Enum):
    elevated = 'elevated'
    unelevated = 'unelevated'


class WindowsWorldWritableWarningNotification(BaseModel):
    extraCount: conint(ge=0)
    failedScan: bool
    samplePaths: list[str]


class ServerNotification3(BaseModel):
    method: Method73 = Field(..., title='Thread/status/changedNotificationMethod')
    params: ThreadStatusChangedNotification


class ServerNotification4(BaseModel):
    method: Method74 = Field(..., title='Thread/archivedNotificationMethod')
    params: ThreadArchivedNotification


class ServerNotification5(BaseModel):
    method: Method75 = Field(..., title='Thread/unarchivedNotificationMethod')
    params: ThreadUnarchivedNotification


class ServerNotification6(BaseModel):
    method: Method76 = Field(..., title='Thread/closedNotificationMethod')
    params: ThreadClosedNotification


class ServerNotification7(BaseModel):
    method: Method77 = Field(..., title='Skills/changedNotificationMethod')
    params: SkillsChangedNotification


class ServerNotification8(BaseModel):
    method: Method78 = Field(..., title='Thread/name/updatedNotificationMethod')
    params: ThreadNameUpdatedNotification


class ServerNotification14(BaseModel):
    method: Method84 = Field(..., title='Turn/diff/updatedNotificationMethod')
    params: TurnDiffUpdatedNotification


class ServerNotification20(BaseModel):
    method: Method90 = Field(..., title='Item/agentMessage/deltaNotificationMethod')
    params: AgentMessageDeltaNotification


class ServerNotification21(BaseModel):
    method: Method91 = Field(..., title='Item/plan/deltaNotificationMethod')
    params: PlanDeltaNotification


class ServerNotification23(BaseModel):
    method: Method93 = Field(
        ..., title='Item/commandExecution/outputDeltaNotificationMethod'
    )
    params: CommandExecutionOutputDeltaNotification


class ServerNotification24(BaseModel):
    method: Method94 = Field(
        ..., title='Item/commandExecution/terminalInteractionNotificationMethod'
    )
    params: TerminalInteractionNotification


class ServerNotification25(BaseModel):
    method: Method95 = Field(..., title='Item/fileChange/outputDeltaNotificationMethod')
    params: FileChangeOutputDeltaNotification


class ServerNotification27(BaseModel):
    method: Method97 = Field(..., title='ServerRequest/resolvedNotificationMethod')
    params: ServerRequestResolvedNotification


class ServerNotification28(BaseModel):
    method: Method98 = Field(..., title='Item/mcpToolCall/progressNotificationMethod')
    params: McpToolCallProgressNotification


class ServerNotification29(BaseModel):
    method: Method99 = Field(
        ..., title='McpServer/oauthLogin/completedNotificationMethod'
    )
    params: McpServerOauthLoginCompletedNotification


class ServerNotification30(BaseModel):
    method: Method100 = Field(
        ..., title='McpServer/startupStatus/updatedNotificationMethod'
    )
    params: McpServerStatusUpdatedNotification


class ServerNotification34(BaseModel):
    method: Method104 = Field(
        ..., title='ExternalAgentConfig/import/completedNotificationMethod'
    )
    params: ExternalAgentConfigImportCompletedNotification


class ServerNotification35(BaseModel):
    method: Method105 = Field(..., title='Fs/changedNotificationMethod')
    params: FsChangedNotification


class ServerNotification36(BaseModel):
    method: Method106 = Field(
        ..., title='Item/reasoning/summaryTextDeltaNotificationMethod'
    )
    params: ReasoningSummaryTextDeltaNotification


class ServerNotification37(BaseModel):
    method: Method107 = Field(
        ..., title='Item/reasoning/summaryPartAddedNotificationMethod'
    )
    params: ReasoningSummaryPartAddedNotification


class ServerNotification38(BaseModel):
    method: Method108 = Field(..., title='Item/reasoning/textDeltaNotificationMethod')
    params: ReasoningTextDeltaNotification


class ServerNotification39(BaseModel):
    method: Method109 = Field(..., title='Thread/compactedNotificationMethod')
    params: ContextCompactedNotification


class ServerNotification40(BaseModel):
    method: Method110 = Field(..., title='Model/reroutedNotificationMethod')
    params: ModelReroutedNotification


class ServerNotification41(BaseModel):
    method: Method111 = Field(..., title='Model/verificationNotificationMethod')
    params: ModelVerificationNotification


class ServerNotification42(BaseModel):
    method: Method112 = Field(..., title='WarningNotificationMethod')
    params: WarningNotification


class ServerNotification43(BaseModel):
    method: Method113 = Field(..., title='GuardianWarningNotificationMethod')
    params: GuardianWarningNotification


class ServerNotification44(BaseModel):
    method: Method114 = Field(..., title='DeprecationNoticeNotificationMethod')
    params: DeprecationNoticeNotification


class ServerNotification46(BaseModel):
    method: Method116 = Field(
        ..., title='FuzzyFileSearch/sessionUpdatedNotificationMethod'
    )
    params: FuzzyFileSearchSessionUpdatedNotification


class ServerNotification47(BaseModel):
    method: Method117 = Field(
        ..., title='FuzzyFileSearch/sessionCompletedNotificationMethod'
    )
    params: FuzzyFileSearchSessionCompletedNotification


class ServerNotification48(BaseModel):
    method: Method118 = Field(..., title='Thread/realtime/startedNotificationMethod')
    params: ThreadRealtimeStartedNotification


class ServerNotification49(BaseModel):
    method: Method119 = Field(..., title='Thread/realtime/itemAddedNotificationMethod')
    params: ThreadRealtimeItemAddedNotification


class ServerNotification50(BaseModel):
    method: Method120 = Field(
        ..., title='Thread/realtime/transcript/deltaNotificationMethod'
    )
    params: ThreadRealtimeTranscriptDeltaNotification


class ServerNotification51(BaseModel):
    method: Method121 = Field(
        ..., title='Thread/realtime/transcript/doneNotificationMethod'
    )
    params: ThreadRealtimeTranscriptDoneNotification


class ServerNotification52(BaseModel):
    method: Method122 = Field(
        ..., title='Thread/realtime/outputAudio/deltaNotificationMethod'
    )
    params: ThreadRealtimeOutputAudioDeltaNotification


class ServerNotification53(BaseModel):
    method: Method123 = Field(..., title='Thread/realtime/sdpNotificationMethod')
    params: ThreadRealtimeSdpNotification


class ServerNotification54(BaseModel):
    method: Method124 = Field(..., title='Thread/realtime/errorNotificationMethod')
    params: ThreadRealtimeErrorNotification


class ServerNotification55(BaseModel):
    method: Method125 = Field(..., title='Thread/realtime/closedNotificationMethod')
    params: ThreadRealtimeClosedNotification


class ServerNotification56(BaseModel):
    method: Method126 = Field(
        ..., title='Windows/worldWritableWarningNotificationMethod'
    )
    params: WindowsWorldWritableWarningNotification


class ServerNotification58(BaseModel):
    method: Method128 = Field(..., title='Account/login/completedNotificationMethod')
    params: AccountLoginCompletedNotification


class AccountUpdatedNotification(BaseModel):
    authMode: AuthMode | None = None
    planType: PlanType | None = None


class AppMetadata(BaseModel):
    categories: list[str] | None = None
    developer: str | None = None
    firstPartyRequiresInstall: bool | None = None
    firstPartyType: str | None = None
    review: AppReview | None = None
    screenshots: list[AppScreenshot] | None = None
    seoDescription: str | None = None
    showInComposerWhenUnlinked: bool | None = None
    subCategories: list[str] | None = None
    version: str | None = None
    versionId: str | None = None
    versionNotes: str | None = None


class ActiveTurnNotSteerable(BaseModel):
    turnKind: NonSteerableTurnKind


class CodexErrorInfo20(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeTurnNotSteerable: ActiveTurnNotSteerable


class CodexErrorInfo14(
    RootModel[
        CodexErrorInfo
        | CodexErrorInfo16
        | CodexErrorInfo17
        | CodexErrorInfo18
        | CodexErrorInfo19
        | CodexErrorInfo20
    ]
):
    root: (
        CodexErrorInfo
        | CodexErrorInfo16
        | CodexErrorInfo17
        | CodexErrorInfo18
        | CodexErrorInfo19
        | CodexErrorInfo20
    ) = Field(
        ...,
        description='This translation layer make sure that we expose codex error code in camel case.\n\nWhen an upstream HTTP status is available (for example, from the Responses API or a provider), it is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.',
    )


class CollabAgentState(BaseModel):
    message: str | None = None
    status: CollabAgentStatus


class CommandExecOutputDeltaNotification(BaseModel):
    capReached: bool = Field(
        ...,
        description='`true` on the final streamed chunk for a stream when `outputBytesCap` truncated later output on that stream.',
    )
    deltaBase64: str = Field(..., description='Base64-encoded output bytes.')
    processId: str = Field(
        ...,
        description='Client-supplied, connection-scoped `processId` from the original `command/exec` request.',
    )
    stream: CommandExecOutputStream = Field(
        ..., description='Output stream for this chunk.'
    )


class ConfigWarningNotification(BaseModel):
    details: str | None = Field(
        None, description='Optional extra guidance or error details.'
    )
    path: str | None = Field(
        None, description='Optional path to the config file that triggered the warning.'
    )
    range: TextRange | None = Field(
        None,
        description='Optional range for the error location inside the config file.',
    )
    summary: str = Field(..., description='Concise summary of the warning.')


class FileSystemPath31(BaseModel):
    type: Type281 = Field(..., title='SpecialFileSystemPathType')
    value: FileSystemSpecialPath


class FileSystemPath28(RootModel[FileSystemPath | FileSystemPath30 | FileSystemPath31]):
    root: FileSystemPath | FileSystemPath30 | FileSystemPath31


class FileSystemSandboxEntry(BaseModel):
    access: FileSystemAccessMode
    path: FileSystemPath28


class FileUpdateChange(BaseModel):
    diff: str
    kind: PatchChangeKind
    path: str


class GuardianApprovalReview(BaseModel):
    rationale: str | None = None
    riskLevel: GuardianRiskLevel | None = None
    status: GuardianApprovalReviewStatus
    userAuthorization: GuardianUserAuthorization | None = None


class GuardianApprovalReviewAction14(BaseModel):
    command: str
    cwd: AbsolutePathBuf
    source: GuardianCommandSource
    type: Type282 = Field(..., title='CommandGuardianApprovalReviewActionType')


class GuardianApprovalReviewAction15(BaseModel):
    argv: list[str]
    cwd: AbsolutePathBuf
    program: str
    source: GuardianCommandSource
    type: Type283 = Field(..., title='ExecveGuardianApprovalReviewActionType')


class GuardianApprovalReviewAction17(BaseModel):
    host: str
    port: conint(ge=0)
    protocol: NetworkApprovalProtocol
    target: str
    type: Type285 = Field(..., title='NetworkAccessGuardianApprovalReviewActionType')


class HookOutputEntry(BaseModel):
    kind: HookOutputEntryKind
    text: str


class HookRunSummary(BaseModel):
    completedAt: int | None = None
    displayOrder: int
    durationMs: int | None = None
    entries: list[HookOutputEntry]
    eventName: HookEventName
    executionMode: HookExecutionMode
    handlerType: HookHandlerType
    id: str
    scope: HookScope
    source: HookSource | None = 'unknown'
    sourcePath: AbsolutePathBuf
    startedAt: int
    status: HookRunStatus
    statusMessage: str | None = None


class HookStartedNotification(BaseModel):
    run: HookRunSummary
    threadId: str
    turnId: str | None = None


class MemoryCitation(BaseModel):
    entries: list[MemoryCitationEntry]
    threadIds: list[str]


class RateLimitSnapshot(BaseModel):
    credits: CreditsSnapshot | None = None
    limitId: str | None = None
    limitName: str | None = None
    planType: PlanType | None = None
    primary: RateLimitWindow | None = None
    rateLimitReachedType: RateLimitReachedType | None = None
    secondary: RateLimitWindow | None = None


class ThreadSpawn(BaseModel):
    agent_nickname: str | None = None
    agent_path: AgentPath | None = None
    agent_role: str | None = None
    depth: int
    parent_thread_id: ThreadId


class SubAgentSource2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    thread_spawn: ThreadSpawn


class SubAgentSource(RootModel[SubAgentSource1 | SubAgentSource2 | SubAgentSource3]):
    root: SubAgentSource1 | SubAgentSource2 | SubAgentSource3


class ThreadItem50(BaseModel):
    content: list[UserInput]
    id: str
    type: Type291 = Field(..., title='UserMessageThreadItemType')


class ThreadItem52(BaseModel):
    id: str
    memoryCitation: MemoryCitation | None = None
    phase: MessagePhase15 | None = None
    text: str
    type: Type293 = Field(..., title='AgentMessageThreadItemType')


class ThreadItem56(BaseModel):
    changes: list[FileUpdateChange]
    id: str
    status: PatchApplyStatus
    type: Type297 = Field(..., title='FileChangeThreadItemType')


class ThreadItem59(BaseModel):
    agentsStates: dict[str, CollabAgentState] = Field(
        ..., description='Last known status of the target agents, when available.'
    )
    id: str = Field(..., description='Unique identifier for this collab tool call.')
    model: str | None = Field(
        None, description='Model requested for the spawned agent, when applicable.'
    )
    prompt: str | None = Field(
        None,
        description='Prompt text sent as part of the collab tool call, when available.',
    )
    reasoningEffort: ReasoningEffort | None = Field(
        None,
        description='Reasoning effort requested for the spawned agent, when applicable.',
    )
    receiverThreadIds: list[str] = Field(
        ...,
        description='Thread ID of the receiving agent, when applicable. In case of spawn operation, this corresponds to the newly spawned agent.',
    )
    senderThreadId: str = Field(
        ..., description='Thread ID of the agent issuing the collab request.'
    )
    status: CollabAgentToolCallStatus = Field(
        ..., description='Current status of the collab tool call.'
    )
    tool: CollabAgentTool = Field(
        ..., description='Name of the collab tool that was invoked.'
    )
    type: Type300 = Field(..., title='CollabAgentToolCallThreadItemType')


class ThreadItem60(BaseModel):
    action: WebSearchAction | None = None
    id: str
    query: str
    type: Type301 = Field(..., title='WebSearchThreadItemType')


class ThreadItem(
    RootModel[
        ThreadItem50
        | ThreadItem51
        | ThreadItem52
        | ThreadItem53
        | ThreadItem54
        | ThreadItem55
        | ThreadItem56
        | ThreadItem57
        | ThreadItem58
        | ThreadItem59
        | ThreadItem60
        | ThreadItem61
        | ThreadItem62
        | ThreadItem63
        | ThreadItem64
        | ThreadItem65
    ]
):
    root: (
        ThreadItem50
        | ThreadItem51
        | ThreadItem52
        | ThreadItem53
        | ThreadItem54
        | ThreadItem55
        | ThreadItem56
        | ThreadItem57
        | ThreadItem58
        | ThreadItem59
        | ThreadItem60
        | ThreadItem61
        | ThreadItem62
        | ThreadItem63
        | ThreadItem64
        | ThreadItem65
    )


class ThreadTokenUsage(BaseModel):
    last: TokenUsageBreakdown
    modelContextWindow: int | None = None
    total: TokenUsageBreakdown


class ThreadTokenUsageUpdatedNotification(BaseModel):
    threadId: str
    tokenUsage: ThreadTokenUsage
    turnId: str


class TurnError(BaseModel):
    additionalDetails: str | None = None
    codexErrorInfo: CodexErrorInfo14 | None = None
    message: str


class TurnPlanStep(BaseModel):
    status: TurnPlanStepStatus
    step: str


class TurnPlanUpdatedNotification(BaseModel):
    explanation: str | None = None
    plan: list[TurnPlanStep]
    threadId: str
    turnId: str


class WindowsSandboxSetupCompletedNotification(BaseModel):
    error: str | None = None
    mode: WindowsSandboxSetupMode
    success: bool


class ServerNotification9(BaseModel):
    method: Method79 = Field(..., title='Thread/tokenUsage/updatedNotificationMethod')
    params: ThreadTokenUsageUpdatedNotification


class ServerNotification11(BaseModel):
    method: Method81 = Field(..., title='Hook/startedNotificationMethod')
    params: HookStartedNotification


class ServerNotification15(BaseModel):
    method: Method85 = Field(..., title='Turn/plan/updatedNotificationMethod')
    params: TurnPlanUpdatedNotification


class ServerNotification22(BaseModel):
    method: Method92 = Field(..., title='Command/exec/outputDeltaNotificationMethod')
    params: CommandExecOutputDeltaNotification


class ServerNotification31(BaseModel):
    method: Method101 = Field(..., title='Account/updatedNotificationMethod')
    params: AccountUpdatedNotification


class ServerNotification45(BaseModel):
    method: Method115 = Field(..., title='ConfigWarningNotificationMethod')
    params: ConfigWarningNotification


class ServerNotification57(BaseModel):
    method: Method127 = Field(
        ..., title='WindowsSandbox/setupCompletedNotificationMethod'
    )
    params: WindowsSandboxSetupCompletedNotification


class AccountRateLimitsUpdatedNotification(BaseModel):
    rateLimits: RateLimitSnapshot


class AdditionalFileSystemPermissions(BaseModel):
    entries: list[FileSystemSandboxEntry] | None = None
    globScanMaxDepth: conint(ge=1) | None = None
    read: list[AbsolutePathBuf] | None = Field(
        None, description='This will be removed in favor of `entries`.'
    )
    write: list[AbsolutePathBuf] | None = Field(
        None, description='This will be removed in favor of `entries`.'
    )


class AppInfo(BaseModel):
    appMetadata: AppMetadata | None = None
    branding: AppBranding | None = None
    description: str | None = None
    distributionChannel: str | None = None
    id: str
    installUrl: str | None = None
    isAccessible: bool | None = False
    isEnabled: bool | None = Field(
        True,
        description='Whether this app is enabled in config.toml. Example: ```toml [apps.bad_app] enabled = false ```',
    )
    labels: dict[str, Any] | None = None
    logoUrl: str | None = None
    logoUrlDark: str | None = None
    name: str
    pluginDisplayNames: list[str] | None = []


class AppListUpdatedNotification(BaseModel):
    data: list[AppInfo]


class ErrorNotification(BaseModel):
    error: TurnError
    threadId: str
    turnId: str
    willRetry: bool


class FileChangePatchUpdatedNotification(BaseModel):
    changes: list[FileUpdateChange]
    itemId: str
    threadId: str
    turnId: str


class HookCompletedNotification(BaseModel):
    run: HookRunSummary
    threadId: str
    turnId: str | None = None


class ItemCompletedNotification(BaseModel):
    item: ThreadItem
    threadId: str
    turnId: str


class ItemStartedNotification(BaseModel):
    item: ThreadItem
    threadId: str
    turnId: str


class RequestPermissionProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fileSystem: AdditionalFileSystemPermissions | None = None
    network: AdditionalNetworkPermissions | None = None


class SessionSource3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subAgent: SubAgentSource


class SessionSource(RootModel[SessionSource1 | SessionSource2 | SessionSource3]):
    root: SessionSource1 | SessionSource2 | SessionSource3


class Turn(BaseModel):
    completedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn completed.'
    )
    durationMs: int | None = Field(
        None,
        description='Duration between turn start and completion in milliseconds, if known.',
    )
    error: TurnError | None = Field(
        None, description="Only populated when the Turn's status is failed."
    )
    id: str
    items: list[ThreadItem] = Field(
        ...,
        description='Only populated on a `thread/resume` or `thread/fork` response. For all other responses and notifications returning a Turn, the items field will be an empty list.',
    )
    startedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn started.'
    )
    status: TurnStatus


class TurnCompletedNotification(BaseModel):
    threadId: str
    turn: Turn


class TurnStartedNotification(BaseModel):
    threadId: str
    turn: Turn


class ServerNotification1(BaseModel):
    method: Method = Field(..., title='ErrorNotificationMethod')
    params: ErrorNotification


class ServerNotification10(BaseModel):
    method: Method80 = Field(..., title='Turn/startedNotificationMethod')
    params: TurnStartedNotification


class ServerNotification12(BaseModel):
    method: Method82 = Field(..., title='Turn/completedNotificationMethod')
    params: TurnCompletedNotification


class ServerNotification13(BaseModel):
    method: Method83 = Field(..., title='Hook/completedNotificationMethod')
    params: HookCompletedNotification


class ServerNotification16(BaseModel):
    method: Method86 = Field(..., title='Item/startedNotificationMethod')
    params: ItemStartedNotification


class ServerNotification19(BaseModel):
    method: Method89 = Field(..., title='Item/completedNotificationMethod')
    params: ItemCompletedNotification


class ServerNotification26(BaseModel):
    method: Method96 = Field(
        ..., title='Item/fileChange/patchUpdatedNotificationMethod'
    )
    params: FileChangePatchUpdatedNotification


class ServerNotification32(BaseModel):
    method: Method102 = Field(..., title='Account/rateLimits/updatedNotificationMethod')
    params: AccountRateLimitsUpdatedNotification


class ServerNotification33(BaseModel):
    method: Method103 = Field(..., title='App/list/updatedNotificationMethod')
    params: AppListUpdatedNotification


class GuardianApprovalReviewAction19(BaseModel):
    permissions: RequestPermissionProfile
    reason: str | None = None
    type: Type287 = Field(
        ..., title='RequestPermissionsGuardianApprovalReviewActionType'
    )


class GuardianApprovalReviewAction13(
    RootModel[
        GuardianApprovalReviewAction14
        | GuardianApprovalReviewAction15
        | GuardianApprovalReviewAction
        | GuardianApprovalReviewAction17
        | GuardianApprovalReviewAction18
        | GuardianApprovalReviewAction19
    ]
):
    root: (
        GuardianApprovalReviewAction14
        | GuardianApprovalReviewAction15
        | GuardianApprovalReviewAction
        | GuardianApprovalReviewAction17
        | GuardianApprovalReviewAction18
        | GuardianApprovalReviewAction19
    )


class ItemGuardianApprovalReviewCompletedNotification(BaseModel):
    action: GuardianApprovalReviewAction13
    decisionSource: AutoReviewDecisionSource
    review: GuardianApprovalReview
    reviewId: str = Field(..., description='Stable identifier for this review.')
    targetItemId: str | None = Field(
        None,
        description='Identifier for the reviewed item or tool call when one exists.\n\nIn most cases, one review maps to one target item. The exceptions are - execve reviews, where a single command may contain multiple execve calls to review (only possible when using the shell_zsh_fork feature) - network policy reviews, where there is no target item\n\nA network call is triggered by a CommandExecution item, so having a target_item_id set to the CommandExecution item would be misleading because the review is about the network call, not the command execution. Therefore, target_item_id is set to None for network policy reviews.',
    )
    threadId: str
    turnId: str


class ItemGuardianApprovalReviewStartedNotification(BaseModel):
    action: GuardianApprovalReviewAction13
    review: GuardianApprovalReview
    reviewId: str = Field(..., description='Stable identifier for this review.')
    targetItemId: str | None = Field(
        None,
        description='Identifier for the reviewed item or tool call when one exists.\n\nIn most cases, one review maps to one target item. The exceptions are - execve reviews, where a single command may contain multiple execve calls to review (only possible when using the shell_zsh_fork feature) - network policy reviews, where there is no target item\n\nA network call is triggered by a CommandExecution item, so having a target_item_id set to the CommandExecution item would be misleading because the review is about the network call, not the command execution. Therefore, target_item_id is set to None for network policy reviews.',
    )
    threadId: str
    turnId: str


class Thread(BaseModel):
    agentNickname: str | None = Field(
        None,
        description='Optional random unique nickname assigned to an AgentControl-spawned sub-agent.',
    )
    agentRole: str | None = Field(
        None,
        description='Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.',
    )
    cliVersion: str = Field(
        ..., description='Version of the CLI that created the thread.'
    )
    createdAt: int = Field(
        ..., description='Unix timestamp (in seconds) when the thread was created.'
    )
    cwd: AbsolutePathBuf = Field(
        ..., description='Working directory captured for the thread.'
    )
    ephemeral: bool = Field(
        ...,
        description='Whether the thread is ephemeral and should not be materialized on disk.',
    )
    forkedFromId: str | None = Field(
        None,
        description='Source thread id when this thread was created by forking another thread.',
    )
    gitInfo: GitInfo | None = Field(
        None, description='Optional Git metadata captured when the thread was created.'
    )
    id: str
    modelProvider: str = Field(
        ..., description="Model provider used for this thread (for example, 'openai')."
    )
    name: str | None = Field(None, description='Optional user-facing thread title.')
    path: str | None = Field(None, description='[UNSTABLE] Path to the thread on disk.')
    preview: str = Field(
        ..., description='Usually the first user message in the thread, if available.'
    )
    source: SessionSource = Field(
        ...,
        description='Origin of the thread (CLI, VSCode, codex exec, codex app-server, etc.).',
    )
    status: ThreadStatus = Field(
        ..., description='Current runtime status for the thread.'
    )
    turns: list[Turn] = Field(
        ...,
        description='Only populated on `thread/resume`, `thread/rollback`, `thread/fork`, and `thread/read` (when `includeTurns` is true) responses. For all other responses and notifications returning a Thread, the turns field will be an empty list.',
    )
    updatedAt: int = Field(
        ..., description='Unix timestamp (in seconds) when the thread was last updated.'
    )


class ThreadStartedNotification(BaseModel):
    thread: Thread


class ServerNotification2(BaseModel):
    method: Method72 = Field(..., title='Thread/startedNotificationMethod')
    params: ThreadStartedNotification


class ServerNotification17(BaseModel):
    method: Method87 = Field(
        ..., title='Item/autoApprovalReview/startedNotificationMethod'
    )
    params: ItemGuardianApprovalReviewStartedNotification


class ServerNotification18(BaseModel):
    method: Method88 = Field(
        ..., title='Item/autoApprovalReview/completedNotificationMethod'
    )
    params: ItemGuardianApprovalReviewCompletedNotification


class ServerNotification(
    RootModel[
        ServerNotification1
        | ServerNotification2
        | ServerNotification3
        | ServerNotification4
        | ServerNotification5
        | ServerNotification6
        | ServerNotification7
        | ServerNotification8
        | ServerNotification9
        | ServerNotification10
        | ServerNotification11
        | ServerNotification12
        | ServerNotification13
        | ServerNotification14
        | ServerNotification15
        | ServerNotification16
        | ServerNotification17
        | ServerNotification18
        | ServerNotification19
        | ServerNotification20
        | ServerNotification21
        | ServerNotification22
        | ServerNotification23
        | ServerNotification24
        | ServerNotification25
        | ServerNotification26
        | ServerNotification27
        | ServerNotification28
        | ServerNotification29
        | ServerNotification30
        | ServerNotification31
        | ServerNotification32
        | ServerNotification33
        | ServerNotification34
        | ServerNotification35
        | ServerNotification36
        | ServerNotification37
        | ServerNotification38
        | ServerNotification39
        | ServerNotification40
        | ServerNotification41
        | ServerNotification42
        | ServerNotification43
        | ServerNotification44
        | ServerNotification45
        | ServerNotification46
        | ServerNotification47
        | ServerNotification48
        | ServerNotification49
        | ServerNotification50
        | ServerNotification51
        | ServerNotification52
        | ServerNotification53
        | ServerNotification54
        | ServerNotification55
        | ServerNotification56
        | ServerNotification57
        | ServerNotification58
    ]
):
    root: (
        ServerNotification1
        | ServerNotification2
        | ServerNotification3
        | ServerNotification4
        | ServerNotification5
        | ServerNotification6
        | ServerNotification7
        | ServerNotification8
        | ServerNotification9
        | ServerNotification10
        | ServerNotification11
        | ServerNotification12
        | ServerNotification13
        | ServerNotification14
        | ServerNotification15
        | ServerNotification16
        | ServerNotification17
        | ServerNotification18
        | ServerNotification19
        | ServerNotification20
        | ServerNotification21
        | ServerNotification22
        | ServerNotification23
        | ServerNotification24
        | ServerNotification25
        | ServerNotification26
        | ServerNotification27
        | ServerNotification28
        | ServerNotification29
        | ServerNotification30
        | ServerNotification31
        | ServerNotification32
        | ServerNotification33
        | ServerNotification34
        | ServerNotification35
        | ServerNotification36
        | ServerNotification37
        | ServerNotification38
        | ServerNotification39
        | ServerNotification40
        | ServerNotification41
        | ServerNotification42
        | ServerNotification43
        | ServerNotification44
        | ServerNotification45
        | ServerNotification46
        | ServerNotification47
        | ServerNotification48
        | ServerNotification49
        | ServerNotification50
        | ServerNotification51
        | ServerNotification52
        | ServerNotification53
        | ServerNotification54
        | ServerNotification55
        | ServerNotification56
        | ServerNotification57
        | ServerNotification58
    ) = Field(
        ...,
        description='Notification sent from the server to the client.',
        title='ServerNotification',
    )
