# generated by datamodel-codegen:
#   filename:  ServerRequest.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class Method(Enum):
    item_commandExecution_requestApproval = 'item/commandExecution/requestApproval'


class Method133(Enum):
    item_fileChange_requestApproval = 'item/fileChange/requestApproval'


class Method134(Enum):
    item_tool_requestUserInput = 'item/tool/requestUserInput'


class Method135(Enum):
    mcpServer_elicitation_request = 'mcpServer/elicitation/request'


class Method136(Enum):
    item_permissions_requestApproval = 'item/permissions/requestApproval'


class Method137(Enum):
    item_tool_call = 'item/tool/call'


class Method138(Enum):
    account_chatgptAuthTokens_refresh = 'account/chatgptAuthTokens/refresh'


class Method139(Enum):
    applyPatchApproval = 'applyPatchApproval'


class Method140(Enum):
    execCommandApproval = 'execCommandApproval'


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class AdditionalFileSystemPermissions(BaseModel):
    read: list[AbsolutePathBuf] | None = None
    write: list[AbsolutePathBuf] | None = None


class AdditionalNetworkPermissions(BaseModel):
    enabled: bool | None = None


class AdditionalPermissionProfile(BaseModel):
    fileSystem: AdditionalFileSystemPermissions | None = None
    network: AdditionalNetworkPermissions | None = None


class ChatgptAuthTokensRefreshReason2(Enum):
    unauthorized = 'unauthorized'


class ChatgptAuthTokensRefreshReason(RootModel[ChatgptAuthTokensRefreshReason2]):
    root: ChatgptAuthTokensRefreshReason2


class Type(Enum):
    read = 'read'


class CommandAction(BaseModel):
    command: str
    name: str
    path: AbsolutePathBuf
    type: Type = Field(..., title='ReadCommandActionType')


class Type280(Enum):
    listFiles = 'listFiles'


class CommandAction27(BaseModel):
    command: str
    path: str | None = None
    type: Type280 = Field(..., title='ListFilesCommandActionType')


class Type281(Enum):
    search = 'search'


class CommandAction28(BaseModel):
    command: str
    path: str | None = None
    query: str | None = None
    type: Type281 = Field(..., title='SearchCommandActionType')


class Type282(Enum):
    unknown = 'unknown'


class CommandAction29(BaseModel):
    command: str
    type: Type282 = Field(..., title='UnknownCommandActionType')


class CommandAction25(
    RootModel[CommandAction | CommandAction27 | CommandAction28 | CommandAction29]
):
    root: CommandAction | CommandAction27 | CommandAction28 | CommandAction29


class CommandExecutionApprovalDecision(Enum):
    accept = 'accept'


class CommandExecutionApprovalDecision15(Enum):
    acceptForSession = 'acceptForSession'


class AcceptWithExecpolicyAmendment(BaseModel):
    execpolicy_amendment: list[str]


class CommandExecutionApprovalDecision16(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    acceptWithExecpolicyAmendment: AcceptWithExecpolicyAmendment


class CommandExecutionApprovalDecision18(Enum):
    decline = 'decline'


class CommandExecutionApprovalDecision19(Enum):
    cancel = 'cancel'


class DynamicToolCallParams(BaseModel):
    arguments: Any
    callId: str
    threadId: str
    tool: str
    turnId: str


class Type283(Enum):
    add = 'add'


class FileChange4(BaseModel):
    content: str
    type: Type283 = Field(..., title='AddFileChangeType')


class Type284(Enum):
    delete = 'delete'


class FileChange5(BaseModel):
    content: str
    type: Type284 = Field(..., title='DeleteFileChangeType')


class Type285(Enum):
    update = 'update'


class FileChange6(BaseModel):
    move_path: str | None = None
    type: Type285 = Field(..., title='UpdateFileChangeType')
    unified_diff: str


class FileChange(RootModel[FileChange4 | FileChange5 | FileChange6]):
    root: FileChange4 | FileChange5 | FileChange6


class FileChangeRequestApprovalParams(BaseModel):
    grantRoot: str | None = Field(
        None,
        description='[UNSTABLE] When set, the agent is asking the user to allow writes under this root for the remainder of the session (unclear if this is honored today).',
    )
    itemId: str
    reason: str | None = Field(
        None,
        description='Optional explanatory reason (e.g. request for extra write access).',
    )
    threadId: str
    turnId: str


class McpElicitationArrayType(Enum):
    array = 'array'


class McpElicitationBooleanType(Enum):
    boolean = 'boolean'


class McpElicitationConstOption(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    const: str
    title: str


class McpElicitationNumberType(Enum):
    number = 'number'
    integer = 'integer'


class McpElicitationObjectType(Enum):
    object = 'object'


class McpElicitationStringFormat(Enum):
    email = 'email'
    uri = 'uri'
    date = 'date'
    date_time = 'date-time'


class McpElicitationStringType(Enum):
    string = 'string'


class McpElicitationTitledEnumItems(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    anyOf: list[McpElicitationConstOption]


class McpElicitationTitledMultiSelectEnumSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: list[str] | None = None
    description: str | None = None
    items: McpElicitationTitledEnumItems
    maxItems: conint(ge=0) | None = None
    minItems: conint(ge=0) | None = None
    title: str | None = None
    type: McpElicitationArrayType


class McpElicitationTitledSingleSelectEnumSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: str | None = None
    description: str | None = None
    oneOf: list[McpElicitationConstOption]
    title: str | None = None
    type: McpElicitationStringType


class McpElicitationUntitledEnumItems(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enum: list[str]
    type: McpElicitationStringType


class McpElicitationUntitledMultiSelectEnumSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: list[str] | None = None
    description: str | None = None
    items: McpElicitationUntitledEnumItems
    maxItems: conint(ge=0) | None = None
    minItems: conint(ge=0) | None = None
    title: str | None = None
    type: McpElicitationArrayType


class McpElicitationUntitledSingleSelectEnumSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: str | None = None
    description: str | None = None
    enum: list[str]
    title: str | None = None
    type: McpElicitationStringType


class Mode(Enum):
    form = 'form'


class Mode3(Enum):
    url = 'url'


class McpServerElicitationRequestParams4(BaseModel):
    serverName: str
    threadId: str
    turnId: str | None = Field(
        None,
        description='Active Codex turn when this elicitation was observed, if app-server could correlate one.\n\nThis is nullable because MCP models elicitation as a standalone server-to-client request identified by the MCP server request id. It may be triggered during a turn, but turn context is app-server correlation rather than part of the protocol identity of the elicitation itself.',
    )
    field_meta: Any | None = Field(None, alias='_meta')
    elicitationId: str
    message: str
    mode: Mode3
    url: str


class NetworkApprovalProtocol(Enum):
    http = 'http'
    https = 'https'
    socks5Tcp = 'socks5Tcp'
    socks5Udp = 'socks5Udp'


class NetworkPolicyRuleAction(Enum):
    allow = 'allow'
    deny = 'deny'


class Type286(Enum):
    read = 'read'


class ParsedCommand5(BaseModel):
    cmd: str
    name: str
    path: str = Field(
        ...,
        description='(Best effort) Path to the file being read by the command. When possible, this is an absolute path, though when relative, it should be resolved against the `cwd`` that will be used to run the command to derive the absolute path.',
    )
    type: Type286 = Field(..., title='ReadParsedCommandType')


class Type287(Enum):
    list_files = 'list_files'


class ParsedCommand6(BaseModel):
    cmd: str
    path: str | None = None
    type: Type287 = Field(..., title='ListFilesParsedCommandType')


class Type288(Enum):
    search = 'search'


class ParsedCommand7(BaseModel):
    cmd: str
    path: str | None = None
    query: str | None = None
    type: Type288 = Field(..., title='SearchParsedCommandType')


class Type289(Enum):
    unknown = 'unknown'


class ParsedCommand8(BaseModel):
    cmd: str
    type: Type289 = Field(..., title='UnknownParsedCommandType')


class ParsedCommand(
    RootModel[ParsedCommand5 | ParsedCommand6 | ParsedCommand7 | ParsedCommand8]
):
    root: ParsedCommand5 | ParsedCommand6 | ParsedCommand7 | ParsedCommand8


class RequestId(RootModel[str | int]):
    root: str | int


class RequestPermissionProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fileSystem: AdditionalFileSystemPermissions | None = None
    network: AdditionalNetworkPermissions | None = None


class ThreadId(RootModel[str]):
    root: str


class ToolRequestUserInputOption(BaseModel):
    description: str
    label: str


class ToolRequestUserInputQuestion(BaseModel):
    header: str
    id: str
    isOther: bool | None = False
    isSecret: bool | None = False
    options: list[ToolRequestUserInputOption] | None = None
    question: str


class ServerRequest2(BaseModel):
    id: RequestId
    method: Method133 = Field(..., title='Item/fileChange/requestApprovalRequestMethod')
    params: FileChangeRequestApprovalParams


class ServerRequest6(BaseModel):
    id: RequestId
    method: Method137 = Field(..., title='Item/tool/callRequestMethod')
    params: DynamicToolCallParams


class ApplyPatchApprovalParams(BaseModel):
    callId: str = Field(
        ...,
        description='Use to correlate this with [codex_protocol::protocol::PatchApplyBeginEvent] and [codex_protocol::protocol::PatchApplyEndEvent].',
    )
    conversationId: ThreadId
    fileChanges: dict[str, FileChange]
    grantRoot: str | None = Field(
        None,
        description='When set, the agent is asking the user to allow writes under this root for the remainder of the session (unclear if this is honored today).',
    )
    reason: str | None = Field(
        None,
        description='Optional explanatory reason (e.g. request for extra write access).',
    )


class ChatgptAuthTokensRefreshParams(BaseModel):
    previousAccountId: str | None = Field(
        None,
        description='Workspace/account identifier that Codex was previously using.\n\nClients that manage multiple accounts/workspaces can use this as a hint to refresh the token for the correct workspace.\n\nThis may be `null` when the prior auth state did not include a workspace identifier (`chatgpt_account_id`).',
    )
    reason: ChatgptAuthTokensRefreshReason


class ExecCommandApprovalParams(BaseModel):
    approvalId: str | None = Field(
        None, description='Identifier for this specific approval callback.'
    )
    callId: str = Field(
        ...,
        description='Use to correlate this with [codex_protocol::protocol::ExecCommandBeginEvent] and [codex_protocol::protocol::ExecCommandEndEvent].',
    )
    command: list[str]
    conversationId: ThreadId
    cwd: str
    parsedCmd: list[ParsedCommand]
    reason: str | None = None


class McpElicitationBooleanSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: bool | None = None
    description: str | None = None
    title: str | None = None
    type: McpElicitationBooleanType


class McpElicitationLegacyTitledEnumSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: str | None = None
    description: str | None = None
    enum: list[str]
    enumNames: list[str] | None = None
    title: str | None = None
    type: McpElicitationStringType


class McpElicitationMultiSelectEnumSchema(
    RootModel[
        McpElicitationUntitledMultiSelectEnumSchema
        | McpElicitationTitledMultiSelectEnumSchema
    ]
):
    root: (
        McpElicitationUntitledMultiSelectEnumSchema
        | McpElicitationTitledMultiSelectEnumSchema
    )


class McpElicitationNumberSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: float | None = None
    description: str | None = None
    maximum: float | None = None
    minimum: float | None = None
    title: str | None = None
    type: McpElicitationNumberType


class McpElicitationSingleSelectEnumSchema(
    RootModel[
        McpElicitationUntitledSingleSelectEnumSchema
        | McpElicitationTitledSingleSelectEnumSchema
    ]
):
    root: (
        McpElicitationUntitledSingleSelectEnumSchema
        | McpElicitationTitledSingleSelectEnumSchema
    )


class McpElicitationStringSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: str | None = None
    description: str | None = None
    format: McpElicitationStringFormat | None = None
    maxLength: conint(ge=0) | None = None
    minLength: conint(ge=0) | None = None
    title: str | None = None
    type: McpElicitationStringType


class NetworkApprovalContext(BaseModel):
    host: str
    protocol: NetworkApprovalProtocol


class NetworkPolicyAmendment(BaseModel):
    action: NetworkPolicyRuleAction
    host: str


class PermissionsRequestApprovalParams(BaseModel):
    itemId: str
    permissions: RequestPermissionProfile
    reason: str | None = None
    threadId: str
    turnId: str


class ToolRequestUserInputParams(BaseModel):
    itemId: str
    questions: list[ToolRequestUserInputQuestion]
    threadId: str
    turnId: str


class ServerRequest3(BaseModel):
    id: RequestId
    method: Method134 = Field(..., title='Item/tool/requestUserInputRequestMethod')
    params: ToolRequestUserInputParams


class ServerRequest5(BaseModel):
    id: RequestId
    method: Method136 = Field(
        ..., title='Item/permissions/requestApprovalRequestMethod'
    )
    params: PermissionsRequestApprovalParams


class ServerRequest7(BaseModel):
    id: RequestId
    method: Method138 = Field(
        ..., title='Account/chatgptAuthTokens/refreshRequestMethod'
    )
    params: ChatgptAuthTokensRefreshParams


class ServerRequest8(BaseModel):
    id: RequestId
    method: Method139 = Field(..., title='ApplyPatchApprovalRequestMethod')
    params: ApplyPatchApprovalParams


class ServerRequest9(BaseModel):
    id: RequestId
    method: Method140 = Field(..., title='ExecCommandApprovalRequestMethod')
    params: ExecCommandApprovalParams


class ApplyNetworkPolicyAmendment(BaseModel):
    network_policy_amendment: NetworkPolicyAmendment


class CommandExecutionApprovalDecision17(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applyNetworkPolicyAmendment: ApplyNetworkPolicyAmendment


class CommandExecutionApprovalDecision13(
    RootModel[
        CommandExecutionApprovalDecision
        | CommandExecutionApprovalDecision15
        | CommandExecutionApprovalDecision16
        | CommandExecutionApprovalDecision17
        | CommandExecutionApprovalDecision18
        | CommandExecutionApprovalDecision19
    ]
):
    root: (
        CommandExecutionApprovalDecision
        | CommandExecutionApprovalDecision15
        | CommandExecutionApprovalDecision16
        | CommandExecutionApprovalDecision17
        | CommandExecutionApprovalDecision18
        | CommandExecutionApprovalDecision19
    )


class CommandExecutionRequestApprovalParams(BaseModel):
    additionalPermissions: AdditionalPermissionProfile | None = Field(
        None, description='Optional additional permissions requested for this command.'
    )
    approvalId: str | None = Field(
        None,
        description='Unique identifier for this specific approval callback.\n\nFor regular shell/unified_exec approvals, this is null.\n\nFor zsh-exec-bridge subcommand approvals, multiple callbacks can belong to one parent `itemId`, so `approvalId` is a distinct opaque callback id (a UUID) used to disambiguate routing.',
    )
    availableDecisions: list[CommandExecutionApprovalDecision13] | None = Field(
        None,
        description='Ordered list of decisions the client may present for this prompt.',
    )
    command: str | None = Field(None, description='The command to be executed.')
    commandActions: list[CommandAction25] | None = Field(
        None, description='Best-effort parsed command actions for friendly display.'
    )
    cwd: AbsolutePathBuf | None = Field(
        None, description="The command's working directory."
    )
    itemId: str
    networkApprovalContext: NetworkApprovalContext | None = Field(
        None, description='Optional context for a managed-network approval prompt.'
    )
    proposedExecpolicyAmendment: list[str] | None = Field(
        None,
        description='Optional proposed execpolicy amendment to allow similar commands without prompting.',
    )
    proposedNetworkPolicyAmendments: list[NetworkPolicyAmendment] | None = Field(
        None,
        description='Optional proposed network policy amendments (allow/deny host) for future requests.',
    )
    reason: str | None = Field(
        None,
        description='Optional explanatory reason (e.g. request for network access).',
    )
    threadId: str
    turnId: str


class McpElicitationEnumSchema(
    RootModel[
        McpElicitationSingleSelectEnumSchema
        | McpElicitationMultiSelectEnumSchema
        | McpElicitationLegacyTitledEnumSchema
    ]
):
    root: (
        McpElicitationSingleSelectEnumSchema
        | McpElicitationMultiSelectEnumSchema
        | McpElicitationLegacyTitledEnumSchema
    )


class McpElicitationPrimitiveSchema(
    RootModel[
        McpElicitationEnumSchema
        | McpElicitationStringSchema
        | McpElicitationNumberSchema
        | McpElicitationBooleanSchema
    ]
):
    root: (
        McpElicitationEnumSchema
        | McpElicitationStringSchema
        | McpElicitationNumberSchema
        | McpElicitationBooleanSchema
    )


class McpElicitationSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str | None = Field(None, alias='$schema')
    properties: dict[str, McpElicitationPrimitiveSchema]
    required: list[str] | None = None
    type: McpElicitationObjectType


class McpServerElicitationRequestParams3(BaseModel):
    serverName: str
    threadId: str
    turnId: str | None = Field(
        None,
        description='Active Codex turn when this elicitation was observed, if app-server could correlate one.\n\nThis is nullable because MCP models elicitation as a standalone server-to-client request identified by the MCP server request id. It may be triggered during a turn, but turn context is app-server correlation rather than part of the protocol identity of the elicitation itself.',
    )
    field_meta: Any | None = Field(None, alias='_meta')
    message: str
    mode: Mode
    requestedSchema: McpElicitationSchema


class McpServerElicitationRequestParams(
    RootModel[McpServerElicitationRequestParams3 | McpServerElicitationRequestParams4]
):
    root: McpServerElicitationRequestParams3 | McpServerElicitationRequestParams4


class ServerRequest1(BaseModel):
    id: RequestId
    method: Method = Field(
        ..., title='Item/commandExecution/requestApprovalRequestMethod'
    )
    params: CommandExecutionRequestApprovalParams


class ServerRequest4(BaseModel):
    id: RequestId
    method: Method135 = Field(..., title='McpServer/elicitation/requestRequestMethod')
    params: McpServerElicitationRequestParams


class ServerRequest(
    RootModel[
        ServerRequest1
        | ServerRequest2
        | ServerRequest3
        | ServerRequest4
        | ServerRequest5
        | ServerRequest6
        | ServerRequest7
        | ServerRequest8
        | ServerRequest9
    ]
):
    root: (
        ServerRequest1
        | ServerRequest2
        | ServerRequest3
        | ServerRequest4
        | ServerRequest5
        | ServerRequest6
        | ServerRequest7
        | ServerRequest8
        | ServerRequest9
    ) = Field(
        ...,
        description='Request initiated from the server and sent to the client.',
        title='ServerRequest',
    )
