# generated by datamodel-codegen:
#   filename:  ToolRequestUserInputParams.json
#   timestamp: 2026-04-30T12:51:04+00:00

from __future__ import annotations

from pydantic import BaseModel


class ToolRequestUserInputOption(BaseModel):
    description: str
    label: str


class ToolRequestUserInputQuestion(BaseModel):
    header: str
    id: str
    isOther: bool | None = False
    isSecret: bool | None = False
    options: list[ToolRequestUserInputOption] | None = None
    question: str


class ToolRequestUserInputParams(BaseModel):
    itemId: str
    questions: list[ToolRequestUserInputQuestion]
    threadId: str
    turnId: str
